-- Account-level bootstrap. Run once with controlled administrative roles.
USE ROLE ACCOUNTADMIN;

CREATE RESOURCE MONITOR IF NOT EXISTS ${RESOURCE_MONITOR}
  WITH CREDIT_QUOTA = ${MONTHLY_CREDIT_QUOTA}
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 50 PERCENT DO NOTIFY
    ON 75 PERCENT DO NOTIFY
    ON 90 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND
    ON 110 PERCENT DO SUSPEND_IMMEDIATE;

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS ${PLATFORM_PREFIX}_${ENVIRONMENT}_PLATFORM_ADMIN;
CREATE ROLE IF NOT EXISTS ${PLATFORM_PREFIX}_${ENVIRONMENT}_SECURITY_ADMIN;
CREATE ROLE IF NOT EXISTS ${PLATFORM_PREFIX}_${ENVIRONMENT}_DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS ${PLATFORM_PREFIX}_${ENVIRONMENT}_DATA_SCIENTIST;
CREATE ROLE IF NOT EXISTS ${PLATFORM_PREFIX}_${ENVIRONMENT}_ANALYST;
CREATE ROLE IF NOT EXISTS ${PLATFORM_PREFIX}_${ENVIRONMENT}_OPERATIONS;
CREATE ROLE IF NOT EXISTS ${PLATFORM_PREFIX}_${ENVIRONMENT}_INGEST_SERVICE;
CREATE ROLE IF NOT EXISTS ${PLATFORM_PREFIX}_${ENVIRONMENT}_TRANSFORM_SERVICE;
CREATE ROLE IF NOT EXISTS ${PLATFORM_PREFIX}_${ENVIRONMENT}_FEATURE_SERVICE;
CREATE ROLE IF NOT EXISTS ${PLATFORM_PREFIX}_${ENVIRONMENT}_CORTEX_SERVICE;
CREATE ROLE IF NOT EXISTS ${PLATFORM_PREFIX}_${ENVIRONMENT}_ORCHESTRATOR_SERVICE;

GRANT ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_PLATFORM_ADMIN TO ROLE SYSADMIN;
GRANT ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_SECURITY_ADMIN TO ROLE SECURITYADMIN;

GRANT ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_INGEST_SERVICE
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_PLATFORM_ADMIN;
GRANT ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_TRANSFORM_SERVICE
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_PLATFORM_ADMIN;
GRANT ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_FEATURE_SERVICE
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_PLATFORM_ADMIN;
GRANT ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_CORTEX_SERVICE
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_PLATFORM_ADMIN;
GRANT ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_ORCHESTRATOR_SERVICE
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_PLATFORM_ADMIN;

GRANT ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_TRANSFORM_SERVICE
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_DATA_ENGINEER;
GRANT ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_FEATURE_SERVICE
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_DATA_SCIENTIST;
GRANT ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_CORTEX_SERVICE
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_ANALYST;
