USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS ${ADMIN_WAREHOUSE}
  WAREHOUSE_SIZE = ${ADMIN_WAREHOUSE_SIZE}
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  RESOURCE_MONITOR = ${RESOURCE_MONITOR}
  STATEMENT_TIMEOUT_IN_SECONDS = 1800
  STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 120
  COMMENT = 'Administrative deployment and controlled maintenance';

CREATE WAREHOUSE IF NOT EXISTS ${INGEST_WAREHOUSE}
  WAREHOUSE_SIZE = ${INGEST_WAREHOUSE_SIZE}
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  RESOURCE_MONITOR = ${RESOURCE_MONITOR}
  STATEMENT_TIMEOUT_IN_SECONDS = 1800
  STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 120
  COMMENT = 'File validation, COPY, and ingestion operations';

CREATE WAREHOUSE IF NOT EXISTS ${TRANSFORM_WAREHOUSE}
  WAREHOUSE_SIZE = ${TRANSFORM_WAREHOUSE_SIZE}
  AUTO_SUSPEND = 120
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  MIN_CLUSTER_COUNT = 1
  MAX_CLUSTER_COUNT = 1
  SCALING_POLICY = ECONOMY
  RESOURCE_MONITOR = ${RESOURCE_MONITOR}
  MAX_CONCURRENCY_LEVEL = 8
  STATEMENT_TIMEOUT_IN_SECONDS = 7200
  STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 300
  COMMENT = 'dbt, Streams, Tasks, Dynamic Tables, and batch transformations';

CREATE WAREHOUSE IF NOT EXISTS ${FEATURE_WAREHOUSE}
  WAREHOUSE_SIZE = ${FEATURE_WAREHOUSE_SIZE}
  AUTO_SUSPEND = 120
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  RESOURCE_MONITOR = ${RESOURCE_MONITOR}
  STATEMENT_TIMEOUT_IN_SECONDS = 7200
  STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 300
  COMMENT = 'Point-in-time feature construction, training set assembly, and scoring';

CREATE WAREHOUSE IF NOT EXISTS ${CORTEX_WAREHOUSE}
  WAREHOUSE_SIZE = ${CORTEX_WAREHOUSE_SIZE}
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  RESOURCE_MONITOR = ${RESOURCE_MONITOR}
  STATEMENT_TIMEOUT_IN_SECONDS = 900
  STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 60
  COMMENT = 'Semantic, governed conversational, and API consumption workloads';
