USE DATABASE ${DATABASE_NAME};

CREATE TABLE IF NOT EXISTS BRONZE.SLOT_EVENTS_RAW (
  RAW_PAYLOAD VARIANT NOT NULL,
  EVENT_ID STRING,
  EVENT_TIME TIMESTAMP_TZ,
  INGESTION_TIME TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
  PROPERTY_ID STRING,
  LOCATION_ID STRING,
  MACHINE_ID STRING,
  EVENT_TYPE STRING,
  AMOUNT NUMBER(18, 2),
  CURRENCY STRING,
  SOURCE_SYSTEM STRING,
  SOURCE_FILE STRING,
  SOURCE_ROW_NUMBER NUMBER,
  KAFKA_TOPIC STRING,
  KAFKA_PARTITION NUMBER,
  KAFKA_OFFSET NUMBER,
  PUBSUB_MESSAGE_ID STRING,
  SCHEMA_VERSION NUMBER,
  LOAD_BATCH_ID STRING,
  RECORD_HASH STRING,
  CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
)
DATA_RETENTION_TIME_IN_DAYS = ${DATA_RETENTION_DAYS}
CHANGE_TRACKING = TRUE;

CREATE TABLE IF NOT EXISTS SILVER.SLOT_EVENTS (
  EVENT_ID STRING NOT NULL,
  EVENT_TIME TIMESTAMP_TZ NOT NULL,
  INGESTION_TIME TIMESTAMP_TZ NOT NULL,
  PROPERTY_ID STRING NOT NULL,
  LOCATION_ID STRING,
  MACHINE_ID STRING NOT NULL,
  EVENT_TYPE STRING NOT NULL,
  AMOUNT NUMBER(18, 2),
  CURRENCY STRING,
  LOAD_BATCH_ID STRING,
  SOURCE_RECORD_HASH STRING,
  CREATED_AT TIMESTAMP_TZ,
  UPDATED_AT TIMESTAMP_TZ,
  PRIMARY KEY (EVENT_ID) NOT ENFORCED
);

CREATE TABLE IF NOT EXISTS SILVER.DIM_PLAYER_SCD2 (
  PLAYER_SK STRING NOT NULL,
  PLAYER_ID STRING NOT NULL,
  LOYALTY_TIER STRING,
  SEGMENT STRING,
  EMAIL STRING,
  HOME_PROPERTY_ID STRING,
  EFFECTIVE_START_DATE DATE NOT NULL,
  EFFECTIVE_END_DATE DATE NOT NULL,
  IS_CURRENT BOOLEAN NOT NULL,
  HASHDIFF STRING NOT NULL,
  CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (PLAYER_SK) NOT ENFORCED
);

CREATE TABLE IF NOT EXISTS GOLD.FACT_GAME_REVENUE_DAILY (
  GAMING_DAY DATE NOT NULL,
  PROPERTY_ID STRING NOT NULL,
  LOCATION_ID STRING NOT NULL,
  GAME_TYPE STRING NOT NULL,
  GROSS_WIN NUMBER(20, 2),
  ADJUSTMENTS NUMBER(20, 2),
  VOIDS NUMBER(20, 2),
  NET_GAMING_REVENUE NUMBER(20, 2),
  SOURCE_MAX_UPDATED_AT TIMESTAMP_TZ,
  LOADED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (GAMING_DAY, PROPERTY_ID, LOCATION_ID, GAME_TYPE) NOT ENFORCED
);

CREATE TABLE IF NOT EXISTS GOLD.FACT_POS_REVENUE_DAILY (
  BUSINESS_DATE DATE,
  PROPERTY_ID STRING,
  LOCATION_ID STRING,
  POS_NET_REVENUE NUMBER(20, 2),
  LOADED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS GOLD.FACT_LABOR_COST_DAILY (
  BUSINESS_DATE DATE,
  PROPERTY_ID STRING,
  LOCATION_ID STRING,
  LABOR_HOURS NUMBER(18, 2),
  LABOR_COST NUMBER(20, 2),
  LOADED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS GOLD.FACT_OFFER_COST_DAILY (
  BUSINESS_DATE DATE,
  PROPERTY_ID STRING,
  LOCATION_ID STRING,
  OFFER_COST NUMBER(20, 2),
  ELIGIBLE_PLAYERS NUMBER,
  CONVERTED_PLAYERS NUMBER,
  LOADED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS FEATURES.FP_PLAYER_VALUE_DAILY (
  PLAYER_ID STRING,
  ANALYSIS_DATE DATE,
  NET_GAMING_REVENUE_30D NUMBER(20, 2),
  ACTIVE_GAMING_DAYS_30D NUMBER,
  LOYALTY_TIER_AS_OF_DATE STRING,
  FEATURE_MAX_EVENT_DATE DATE,
  FEATURE_BUILT_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (PLAYER_ID, ANALYSIS_DATE) NOT ENFORCED
);

CREATE TABLE IF NOT EXISTS ML.PLAYER_VALUE_TRAINING_SET (
  PLAYER_ID STRING,
  ANALYSIS_DATE DATE,
  NET_GAMING_REVENUE_30D NUMBER(20, 2),
  ACTIVE_GAMING_DAYS_30D NUMBER,
  LOYALTY_TIER_AS_OF_DATE STRING,
  NEXT_30D_VALUE NUMBER(20, 2),
  SPLIT STRING,
  FEATURE_MAX_EVENT_DATE DATE,
  LABEL_START_DATE DATE,
  LABEL_END_DATE DATE,
  BUILT_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS ML.MODEL_SCORES (
  ENTITY_TYPE STRING,
  ENTITY_ID STRING,
  MODEL_NAME STRING,
  MODEL_VERSION STRING,
  FEATURE_AS_OF TIMESTAMP_TZ,
  SCORED_AT TIMESTAMP_TZ,
  SCORE FLOAT,
  PREDICTION VARIANT,
  REQUEST_ID STRING,
  TRACE_ID STRING,
  CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (ENTITY_TYPE, ENTITY_ID, MODEL_NAME, MODEL_VERSION, FEATURE_AS_OF) NOT ENFORCED
);

CREATE TABLE IF NOT EXISTS OPS.PIPELINE_RUN (
  RUN_ID STRING,
  PIPELINE_NAME STRING,
  ENVIRONMENT STRING,
  DATA_INTERVAL_START TIMESTAMP_TZ,
  DATA_INTERVAL_END TIMESTAMP_TZ,
  CODE_VERSION STRING,
  STATUS STRING,
  ROWS_READ NUMBER,
  ROWS_WRITTEN NUMBER,
  ROWS_REJECTED NUMBER,
  STARTED_AT TIMESTAMP_TZ,
  ENDED_AT TIMESTAMP_TZ,
  ERROR_MESSAGE STRING,
  TRACE_ID STRING
);

CREATE TABLE IF NOT EXISTS OPS.DQ_RESULT (
  RUN_ID STRING,
  CHECK_TS TIMESTAMP_TZ,
  OBJECT_NAME STRING,
  CHECK_NAME STRING,
  STATUS STRING,
  SEVERITY STRING,
  FAILED_COUNT NUMBER,
  DETAILS VARIANT
);

CREATE TABLE IF NOT EXISTS OPS.CONTRACT_RESULT (
  CONTRACT_NAME STRING,
  CONTRACT_VERSION STRING,
  VALIDATED_AT TIMESTAMP_TZ,
  STATUS STRING,
  FAILURE_COUNT NUMBER,
  DETAILS VARIANT
);

CREATE TABLE IF NOT EXISTS OPS.ROLE_PROPERTY_ACCESS (
  ROLE_NAME STRING,
  PROPERTY_ID STRING,
  ACTIVE BOOLEAN DEFAULT TRUE,
  CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS QUARANTINE.SLOT_EVENTS_REJECTED (
  RAW_PAYLOAD VARIANT,
  REJECTION_REASON STRING,
  SOURCE_SYSTEM STRING,
  LOAD_BATCH_ID STRING,
  REJECTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);
