USE DATABASE ${DATABASE_NAME};

CREATE STREAM IF NOT EXISTS BRONZE.SLOT_EVENTS_STREAM
  ON TABLE BRONZE.SLOT_EVENTS_RAW
  APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK OPS.MERGE_SLOT_EVENTS_TASK
  WAREHOUSE = ${TRANSFORM_WAREHOUSE}
  USER_TASK_TIMEOUT_MS = 900000
  SUSPEND_TASK_AFTER_NUM_FAILURES = 3
  WHEN SYSTEM$STREAM_HAS_DATA('${DATABASE_NAME}.BRONZE.SLOT_EVENTS_STREAM')
AS
MERGE INTO SILVER.SLOT_EVENTS AS target
USING (
  SELECT
    EVENT_ID,
    EVENT_TIME,
    INGESTION_TIME,
    COALESCE(PROPERTY_ID, RAW_PAYLOAD:property_id::STRING) AS PROPERTY_ID,
    COALESCE(LOCATION_ID, RAW_PAYLOAD:location_id::STRING) AS LOCATION_ID,
    COALESCE(MACHINE_ID, RAW_PAYLOAD:machine_id::STRING) AS MACHINE_ID,
    COALESCE(EVENT_TYPE, RAW_PAYLOAD:event_type::STRING) AS EVENT_TYPE,
    COALESCE(AMOUNT, TRY_TO_DECIMAL(RAW_PAYLOAD:amount, 18, 2)) AS AMOUNT,
    COALESCE(CURRENCY, RAW_PAYLOAD:currency::STRING, 'USD') AS CURRENCY,
    LOAD_BATCH_ID,
    RECORD_HASH,
    ROW_NUMBER() OVER (
      PARTITION BY EVENT_ID
      ORDER BY EVENT_TIME DESC, INGESTION_TIME DESC, RECORD_HASH DESC
    ) AS ROW_RANK
  FROM BRONZE.SLOT_EVENTS_STREAM
  WHERE METADATA$ACTION = 'INSERT'
  QUALIFY ROW_RANK = 1
) AS source
ON target.EVENT_ID = source.EVENT_ID
WHEN MATCHED AND target.SOURCE_RECORD_HASH <> source.RECORD_HASH THEN UPDATE SET
  EVENT_TIME = source.EVENT_TIME,
  INGESTION_TIME = source.INGESTION_TIME,
  PROPERTY_ID = source.PROPERTY_ID,
  LOCATION_ID = source.LOCATION_ID,
  MACHINE_ID = source.MACHINE_ID,
  EVENT_TYPE = source.EVENT_TYPE,
  AMOUNT = source.AMOUNT,
  CURRENCY = source.CURRENCY,
  LOAD_BATCH_ID = source.LOAD_BATCH_ID,
  SOURCE_RECORD_HASH = source.RECORD_HASH,
  UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  EVENT_ID,
  EVENT_TIME,
  INGESTION_TIME,
  PROPERTY_ID,
  LOCATION_ID,
  MACHINE_ID,
  EVENT_TYPE,
  AMOUNT,
  CURRENCY,
  LOAD_BATCH_ID,
  SOURCE_RECORD_HASH,
  CREATED_AT,
  UPDATED_AT
) VALUES (
  source.EVENT_ID,
  source.EVENT_TIME,
  source.INGESTION_TIME,
  source.PROPERTY_ID,
  source.LOCATION_ID,
  source.MACHINE_ID,
  source.EVENT_TYPE,
  source.AMOUNT,
  source.CURRENCY,
  source.LOAD_BATCH_ID,
  source.RECORD_HASH,
  CURRENT_TIMESTAMP(),
  CURRENT_TIMESTAMP()
);

-- Deliberately left suspended after deployment. Resume through snowflake/ops/resume_tasks.sql.
