USE DATABASE ${DATABASE_NAME};

CREATE OR REPLACE DYNAMIC TABLE GOLD.FACT_SLOT_PERFORMANCE_5MIN
  TARGET_LAG = '5 minutes'
  WAREHOUSE = ${TRANSFORM_WAREHOUSE}
  REFRESH_MODE = AUTO
  INITIALIZE = ON_SCHEDULE
  CLUSTER BY (TO_DATE(WINDOW_START), PROPERTY_ID)
AS
WITH windowed AS (
  SELECT
    DATEADD(
      'minute',
      5 * FLOOR(DATE_PART('minute', EVENT_TIME) / 5),
      DATE_TRUNC('hour', EVENT_TIME)
    ) AS WINDOW_START,
    PROPERTY_ID,
    LOCATION_ID,
    MACHINE_ID,
    EVENT_TYPE,
    AMOUNT,
    INGESTION_TIME
  FROM SILVER.SLOT_EVENTS
)
SELECT
  WINDOW_START,
  DATEADD('minute', 5, WINDOW_START) AS WINDOW_END,
  PROPERTY_ID,
  LOCATION_ID,
  MACHINE_ID,
  COUNT(*) AS EVENT_COUNT,
  COUNT_IF(EVENT_TYPE = 'SPIN') AS SPIN_COUNT,
  SUM(IFF(EVENT_TYPE = 'COIN_IN', COALESCE(AMOUNT, 0), 0)) AS COIN_IN,
  SUM(IFF(EVENT_TYPE = 'COIN_OUT', COALESCE(AMOUNT, 0), 0)) AS COIN_OUT,
  SUM(IFF(EVENT_TYPE = 'JACKPOT', COALESCE(AMOUNT, 0), 0)) AS JACKPOT_AMOUNT,
  COUNT_IF(EVENT_TYPE = 'FAULT') AS FAULT_COUNT,
  MAX(INGESTION_TIME) AS SOURCE_MAX_INGESTION_TIME
FROM windowed
GROUP BY WINDOW_START, PROPERTY_ID, LOCATION_ID, MACHINE_ID;

CREATE OR REPLACE DYNAMIC TABLE SEMANTIC.LOCATION_PROFITABILITY_DAILY
  TARGET_LAG = '1 hour'
  WAREHOUSE = ${TRANSFORM_WAREHOUSE}
  REFRESH_MODE = AUTO
  INITIALIZE = ON_SCHEDULE
AS
WITH gaming AS (
  SELECT
    GAMING_DAY AS BUSINESS_DATE,
    PROPERTY_ID,
    LOCATION_ID,
    SUM(NET_GAMING_REVENUE) AS NET_GAMING_REVENUE
  FROM GOLD.FACT_GAME_REVENUE_DAILY
  GROUP BY GAMING_DAY, PROPERTY_ID, LOCATION_ID
),
pos AS (
  SELECT BUSINESS_DATE, PROPERTY_ID, LOCATION_ID, SUM(POS_NET_REVENUE) AS POS_NET_REVENUE
  FROM GOLD.FACT_POS_REVENUE_DAILY
  GROUP BY BUSINESS_DATE, PROPERTY_ID, LOCATION_ID
),
labor AS (
  SELECT BUSINESS_DATE, PROPERTY_ID, LOCATION_ID, SUM(LABOR_COST) AS LABOR_COST
  FROM GOLD.FACT_LABOR_COST_DAILY
  GROUP BY BUSINESS_DATE, PROPERTY_ID, LOCATION_ID
),
offers AS (
  SELECT BUSINESS_DATE, PROPERTY_ID, LOCATION_ID, SUM(OFFER_COST) AS OFFER_COST
  FROM GOLD.FACT_OFFER_COST_DAILY
  GROUP BY BUSINESS_DATE, PROPERTY_ID, LOCATION_ID
)
SELECT
  gaming.BUSINESS_DATE,
  gaming.PROPERTY_ID,
  gaming.LOCATION_ID,
  gaming.NET_GAMING_REVENUE,
  COALESCE(pos.POS_NET_REVENUE, 0) AS POS_NET_REVENUE,
  COALESCE(labor.LABOR_COST, 0) AS LABOR_COST,
  COALESCE(offers.OFFER_COST, 0) AS OFFER_COST,
  gaming.NET_GAMING_REVENUE
    + COALESCE(pos.POS_NET_REVENUE, 0)
    - COALESCE(labor.LABOR_COST, 0)
    - COALESCE(offers.OFFER_COST, 0) AS ESTIMATED_LOCATION_PROFIT
FROM gaming
LEFT JOIN pos USING (BUSINESS_DATE, PROPERTY_ID, LOCATION_ID)
LEFT JOIN labor USING (BUSINESS_DATE, PROPERTY_ID, LOCATION_ID)
LEFT JOIN offers USING (BUSINESS_DATE, PROPERTY_ID, LOCATION_ID);
