-- Controlled policy deployment requires policy application privileges.
USE ROLE ACCOUNTADMIN;

USE DATABASE ${DATABASE_NAME};

CREATE OR REPLACE MASKING POLICY OPS.EMAIL_MASKING_POLICY
AS (value STRING)
RETURNS STRING ->
  CASE
    WHEN IS_ROLE_IN_SESSION('${PLATFORM_PREFIX}_${ENVIRONMENT}_SECURITY_ADMIN') THEN value
    WHEN IS_ROLE_IN_SESSION('${PLATFORM_PREFIX}_${ENVIRONMENT}_DATA_ENGINEER') THEN value
    ELSE REGEXP_REPLACE(value, '(^.).*(@.*$)', '\\1***\\2')
  END;

ALTER TABLE SILVER.DIM_PLAYER_SCD2
  MODIFY COLUMN EMAIL
  SET MASKING POLICY OPS.EMAIL_MASKING_POLICY;

CREATE OR REPLACE ROW ACCESS POLICY OPS.PROPERTY_ACCESS_POLICY
AS (property_id STRING)
RETURNS BOOLEAN ->
  IS_ROLE_IN_SESSION('${PLATFORM_PREFIX}_${ENVIRONMENT}_PLATFORM_ADMIN')
  OR IS_ROLE_IN_SESSION('${PLATFORM_PREFIX}_${ENVIRONMENT}_SECURITY_ADMIN')
  OR EXISTS (
    SELECT 1
    FROM OPS.ROLE_PROPERTY_ACCESS AS access_map
    WHERE access_map.ROLE_NAME = CURRENT_ROLE()
      AND access_map.PROPERTY_ID = property_id
      AND access_map.ACTIVE
  );

ALTER DYNAMIC TABLE GOLD.FACT_SLOT_PERFORMANCE_5MIN
  ADD ROW ACCESS POLICY OPS.PROPERTY_ACCESS_POLICY ON (PROPERTY_ID);

ALTER DYNAMIC TABLE SEMANTIC.LOCATION_PROFITABILITY_DAILY
  ADD ROW ACCESS POLICY OPS.PROPERTY_ACCESS_POLICY ON (PROPERTY_ID);
