USE DATABASE ${DATABASE_NAME};

CREATE OR REPLACE VIEW OPS.V_PIPELINE_HEALTH AS
SELECT
  PIPELINE_NAME,
  ENVIRONMENT,
  MAX_BY(STATUS, STARTED_AT) AS LATEST_STATUS,
  MAX(STARTED_AT) AS LATEST_START,
  MAX(ENDED_AT) AS LATEST_END,
  DATEDIFF('minute', MAX(STARTED_AT), CURRENT_TIMESTAMP()) AS MINUTES_SINCE_LATEST_START,
  SUM(IFF(STATUS = 'FAILED' AND STARTED_AT >= DATEADD('day', -7, CURRENT_TIMESTAMP()), 1, 0))
    AS FAILURES_LAST_7_DAYS
FROM OPS.PIPELINE_RUN
GROUP BY PIPELINE_NAME, ENVIRONMENT;

CREATE OR REPLACE VIEW OPS.V_DQ_HEALTH AS
SELECT
  OBJECT_NAME,
  CHECK_NAME,
  MAX_BY(STATUS, CHECK_TS) AS LATEST_STATUS,
  MAX(CHECK_TS) AS LATEST_CHECK_TS,
  SUM(IFF(STATUS = 'FAIL' AND CHECK_TS >= DATEADD('day', -7, CURRENT_TIMESTAMP()), 1, 0))
    AS FAILURES_LAST_7_DAYS
FROM OPS.DQ_RESULT
GROUP BY OBJECT_NAME, CHECK_NAME;

CREATE OR REPLACE VIEW OPS.V_WAREHOUSE_COST_DAILY AS
SELECT
  START_TIME::DATE AS USAGE_DATE,
  WAREHOUSE_NAME,
  SUM(CREDITS_USED) AS CREDITS_USED,
  SUM(CREDITS_USED_COMPUTE) AS COMPUTE_CREDITS,
  SUM(CREDITS_USED_CLOUD_SERVICES) AS CLOUD_SERVICES_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('day', -90, CURRENT_TIMESTAMP())
GROUP BY START_TIME::DATE, WAREHOUSE_NAME;

CREATE OR REPLACE VIEW OPS.V_QUERY_PERFORMANCE AS
SELECT
  QUERY_ID,
  QUERY_TAG,
  WAREHOUSE_NAME,
  USER_NAME,
  ROLE_NAME,
  TOTAL_ELAPSED_TIME,
  BYTES_SCANNED,
  PARTITIONS_SCANNED,
  PARTITIONS_TOTAL,
  QUEUED_OVERLOAD_TIME,
  EXECUTION_STATUS,
  START_TIME
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP());
