USE ROLE SECURITYADMIN;

-- Warehouse privileges are granted by workload. Runtime services do not receive ACCOUNTADMIN.
GRANT USAGE, OPERATE ON WAREHOUSE ${INGEST_WAREHOUSE}
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_INGEST_SERVICE;
GRANT USAGE, OPERATE ON WAREHOUSE ${TRANSFORM_WAREHOUSE}
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_TRANSFORM_SERVICE;
GRANT USAGE, OPERATE ON WAREHOUSE ${FEATURE_WAREHOUSE}
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_FEATURE_SERVICE;
GRANT USAGE ON WAREHOUSE ${CORTEX_WAREHOUSE}
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_CORTEX_SERVICE;
GRANT USAGE, OPERATE ON WAREHOUSE ${ADMIN_WAREHOUSE}
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_PLATFORM_ADMIN;

GRANT USAGE ON DATABASE ${DATABASE_NAME}
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_INGEST_SERVICE;
GRANT USAGE ON DATABASE ${DATABASE_NAME}
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_TRANSFORM_SERVICE;
GRANT USAGE ON DATABASE ${DATABASE_NAME}
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_FEATURE_SERVICE;
GRANT USAGE ON DATABASE ${DATABASE_NAME}
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_CORTEX_SERVICE;
GRANT USAGE ON DATABASE ${DATABASE_NAME}
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_PLATFORM_ADMIN;

GRANT USAGE ON SCHEMA ${DATABASE_NAME}.BRONZE
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_INGEST_SERVICE;
GRANT USAGE ON SCHEMA ${DATABASE_NAME}.QUARANTINE
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_INGEST_SERVICE;
GRANT USAGE ON SCHEMA ${DATABASE_NAME}.OPS
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_INGEST_SERVICE;
GRANT USAGE ON SCHEMA ${DATABASE_NAME}.TEMP
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_INGEST_SERVICE;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA ${DATABASE_NAME}.BRONZE
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_INGEST_SERVICE;
GRANT SELECT, INSERT ON FUTURE TABLES IN SCHEMA ${DATABASE_NAME}.BRONZE
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_INGEST_SERVICE;
GRANT INSERT ON ALL TABLES IN SCHEMA ${DATABASE_NAME}.QUARANTINE
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_INGEST_SERVICE;
GRANT INSERT ON FUTURE TABLES IN SCHEMA ${DATABASE_NAME}.QUARANTINE
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_INGEST_SERVICE;

GRANT USAGE ON ALL SCHEMAS IN DATABASE ${DATABASE_NAME}
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_TRANSFORM_SERVICE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ${DATABASE_NAME}
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_TRANSFORM_SERVICE;
GRANT SELECT ON ALL TABLES IN SCHEMA ${DATABASE_NAME}.BRONZE
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_TRANSFORM_SERVICE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ${DATABASE_NAME}.BRONZE
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_TRANSFORM_SERVICE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA ${DATABASE_NAME}.SILVER
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_TRANSFORM_SERVICE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA ${DATABASE_NAME}.SILVER
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_TRANSFORM_SERVICE;
GRANT SELECT ON ALL TABLES IN SCHEMA ${DATABASE_NAME}.GOLD
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_TRANSFORM_SERVICE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ${DATABASE_NAME}.GOLD
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_TRANSFORM_SERVICE;

GRANT USAGE ON SCHEMA ${DATABASE_NAME}.FEATURES
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_FEATURE_SERVICE;
GRANT USAGE ON SCHEMA ${DATABASE_NAME}.ML
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_FEATURE_SERVICE;
GRANT USAGE ON SCHEMA ${DATABASE_NAME}.GOLD
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_FEATURE_SERVICE;
GRANT SELECT ON ALL TABLES IN SCHEMA ${DATABASE_NAME}.GOLD
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_FEATURE_SERVICE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ${DATABASE_NAME}.GOLD
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_FEATURE_SERVICE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ${DATABASE_NAME}.FEATURES
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_FEATURE_SERVICE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ${DATABASE_NAME}.FEATURES
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_FEATURE_SERVICE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ${DATABASE_NAME}.ML
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_FEATURE_SERVICE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ${DATABASE_NAME}.ML
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_FEATURE_SERVICE;

GRANT USAGE ON SCHEMA ${DATABASE_NAME}.GOLD
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_CORTEX_SERVICE;
GRANT USAGE ON SCHEMA ${DATABASE_NAME}.SEMANTIC
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_CORTEX_SERVICE;
GRANT SELECT ON ALL TABLES IN SCHEMA ${DATABASE_NAME}.GOLD
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_CORTEX_SERVICE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ${DATABASE_NAME}.GOLD
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_CORTEX_SERVICE;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA ${DATABASE_NAME}.SEMANTIC
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_CORTEX_SERVICE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ${DATABASE_NAME}.SEMANTIC
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_CORTEX_SERVICE;

GRANT USAGE ON DATABASE ${DATABASE_NAME}
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_ANALYST;
GRANT USAGE ON SCHEMA ${DATABASE_NAME}.GOLD
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_ANALYST;
GRANT USAGE ON SCHEMA ${DATABASE_NAME}.SEMANTIC
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA ${DATABASE_NAME}.GOLD
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ${DATABASE_NAME}.GOLD
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_ANALYST;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA ${DATABASE_NAME}.SEMANTIC
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_ANALYST;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ${DATABASE_NAME}.SEMANTIC
  TO ROLE ${PLATFORM_PREFIX}_${ENVIRONMENT}_ANALYST;
