USE ROLE SYSADMIN;

USE DATABASE ${DATABASE_NAME};

CREATE OR REPLACE VIEW OPS.V_FOUNDATION_VALIDATION AS
SELECT 'DATABASE_EXISTS' AS CHECK_NAME, COUNT_IF(DATABASE_NAME = '${DATABASE_NAME}') AS MATCH_COUNT
FROM ${DATABASE_NAME}.INFORMATION_SCHEMA.DATABASES
UNION ALL
SELECT 'EXPECTED_SCHEMAS', COUNT_IF(SCHEMA_NAME IN (
  'BRONZE', 'SILVER', 'GOLD', 'SEMANTIC', 'FEATURES', 'ML', 'OPS', 'QUARANTINE', 'TEMP'
))
FROM ${DATABASE_NAME}.INFORMATION_SCHEMA.SCHEMATA
UNION ALL
SELECT 'EXPECTED_CORE_TABLES', COUNT_IF(TABLE_NAME IN (
  'SLOT_EVENTS_RAW', 'SLOT_EVENTS', 'FACT_GAME_REVENUE_DAILY',
  'FP_PLAYER_VALUE_DAILY', 'MODEL_SCORES', 'PIPELINE_RUN', 'DQ_RESULT'
))
FROM ${DATABASE_NAME}.INFORMATION_SCHEMA.TABLES;
