(() => {
  const $ = id => document.getElementById(id);
  const labs = [
    ['Neon Harbor Production Control Room','Daily shift, scenario switching, Snowflake console, Databricks workbook, incident drills, file map, and graded handoff.','/simulators/neon-harbor-production.html','Production','featured'],
    ['Broken Pipeline: 30 Defects','Fix lag, schema drift, state growth, driver OOM, join explosions, Snowflake cost, dbt misses, serving failures, CI/CD and recovery.','/simulators/broken-pipeline-30.html','30 Defects','featured'],
    ['Daily Operations SOP','Ordered production health, quality, deployment, verification, recovery, and handoff workflow.','/simulators/daily-operations.html','Daily','']
  ];
  function showToast(text){let old=document.querySelector('.lab-score-toast');if(old)old.remove();let d=document.createElement('div');d.className='lab-score-toast';d.innerHTML='<strong>OpsReady evidence captured</strong><div style="margin-top:4px">'+text+'</div>';document.body.appendChild(d);setTimeout(()=>d.remove(),4200)}
  function openModal(title,url){if(!$('simModal'))return;$('simTitle').textContent=title;$('simFrame').src=url;$('simModal').classList.remove('hidden')}
  if($('closeSim'))$('closeSim').onclick=()=>{$('simModal').classList.add('hidden');$('simFrame').src='about:blank'};
  function renderLibrary(){let host=$('simulatorCards');if(!host)return;host.innerHTML='';labs.forEach(([title,desc,url,badge,cls])=>{let c=document.createElement('article');c.className='sim-card '+cls;c.innerHTML=`<div class="lab-meta"><span class="pill">${badge}</span><span class="pill">Interactive</span></div><h3>${title}</h3><p class="muted">${desc}</p><button class="btn btn-primary">Launch Full Lab</button>`;c.querySelector('button').onclick=()=>openModal(title,url);host.appendChild(c)})}
  let controlUrl='/simulators/neon-harbor-production.html',controlTitle='Neon Harbor Production Control Room';
  document.querySelectorAll('.control-launch').forEach(b=>b.onclick=()=>{document.querySelectorAll('.control-launch').forEach(x=>x.classList.remove('active'));b.classList.add('active');controlUrl=b.dataset.src;controlTitle=b.dataset.title;$('controlFrame').src=controlUrl;$('controlTitle').textContent=controlTitle});
  if($('openControlFull'))$('openControlFull').onclick=()=>openModal(controlTitle,controlUrl);
  function capture(){let f=$('controlFrame');if(!f)return;try{let doc=f.contentDocument,score=null,detail='';if(controlUrl.includes('broken-pipeline')){let s=doc.getElementById('score'),fx=doc.getElementById('fixed');score=s?parseInt(s.textContent)||0:0;detail=(fx?fx.textContent:'')+' fixed; diagnosis '+score+'%';let fixedPct=0;if(fx){let m=fx.textContent.match(/(\d+)\s*\/\s*(\d+)/);if(m)fixedPct=Number(m[1])/Number(m[2])*100}score=Math.round(score*.6+fixedPct*.4)}else if(controlUrl.includes('neon-harbor')){let pct=doc.getElementById('pct'),hs=doc.getElementById('handoffScore');let completion=pct?parseInt(pct.textContent)||0:0,hand=0;if(hs&&hs.textContent){let m=hs.textContent.match(/(\d+)%/);if(m)hand=Number(m[1])}score=Math.round(completion*.65+hand*.35);detail=`shift ${completion}% + handoff ${hand}%`}else{score=100;detail='lab opened / evidence reviewed'}if($('labScore'))$('labScore').textContent=score+'%';if($('labScoreSub'))$('labScoreSub').textContent=detail;let hist=JSON.parse(localStorage.getItem('opsreadyLabEvidence')||'[]');hist.push({lab:controlTitle,score,detail,at:new Date().toISOString()});localStorage.setItem('opsreadyLabEvidence',JSON.stringify(hist.slice(-50)));showToast(`${controlTitle}: ${score}% — ${detail}`)}catch(e){showToast('The lab is running, but its score could not be read yet. Complete/grade the lab first, then capture again.')}}
  if($('captureLabScore'))$('captureLabScore').onclick=capture;
  window.addEventListener('message',e=>{if(!e.data||e.data.type!=='opsready-lab-score')return;let score=Math.round(Number(e.data.score)||0),detail=e.data.detail||e.data.lab||'Interactive lab';if($('labScore'))$('labScore').textContent=score+'%';if($('labScoreSub'))$('labScoreSub').textContent=detail;showToast(`${e.data.lab||'Lab'}: ${score}%`)});
  renderLibrary();
})();
