USE DATABASE ${DATABASE_NAME};

SELECT * FROM OPS.V_FOUNDATION_VALIDATION ORDER BY CHECK_NAME;

SHOW WAREHOUSES LIKE '${PLATFORM_PREFIX}_${ENVIRONMENT}_%_WH';
SHOW RESOURCE MONITORS LIKE '${RESOURCE_MONITOR}';
SHOW ROLES LIKE '${PLATFORM_PREFIX}_${ENVIRONMENT}_%';

SELECT
  CURRENT_ACCOUNT() AS ACCOUNT_NAME,
  CURRENT_DATABASE() AS DATABASE_NAME,
  CURRENT_ROLE() AS ACTIVE_ROLE,
  CURRENT_WAREHOUSE() AS ACTIVE_WAREHOUSE;
