(() => {
  const byId=id=>document.getElementById(id);
  const nav=byId('nav'), main=document.querySelector('main');
  if(!nav||!main) return;

  const categories=['SQL','PySpark','Tests','dbt','API','Dev','Triage'];
  let progress={};
  try{progress=JSON.parse(localStorage.getItem('opsreadyAdvancedProgress')||'{}')}catch(e){progress={}}
  categories.forEach(c=>{if(!progress[c])progress[c]={}});
  const save=()=>localStorage.setItem('opsreadyAdvancedProgress',JSON.stringify(progress));
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

  const banks={
    SQL:[
      {title:'Customers with no orders',level:'Core',prompt:'Return customers who have never placed an order. Preserve one row per customer.',starter:'SELECT c.customer_id\nFROM customer c\nJOIN orders o ON c.customer_id=o.customer_id;',criteria:[['Anti-join pattern',/not\s+exists|left\s+join/i],['No-match filter',/not\s+exists|is\s+null/i]],reference:'SELECT c.customer_id\nFROM customer c\nWHERE NOT EXISTS (\n  SELECT 1 FROM orders o\n  WHERE o.customer_id=c.customer_id\n);',output:'Rows: 18,402 customers\nGrain: one row per customer\nPASS: no order-side duplication.'},
      {title:'Deterministic latest record',level:'Core',prompt:'Return the latest tier row per customer using effective_at and source_sequence as a tie breaker.',starter:'SELECT * FROM customer_tier;',criteria:[['ROW_NUMBER window',/row_number\s*\(/i],['Partition by customer',/partition\s+by\s+customer_id/i],['Deterministic descending order',/order\s+by[\s\S]*(effective_at|source_sequence)[\s\S]*desc/i],['Keep row one',/qualify[\s\S]*=\s*1|where[\s\S]*rn\s*=\s*1/i]],reference:'SELECT *\nFROM customer_tier\nQUALIFY ROW_NUMBER() OVER (\n  PARTITION BY customer_id\n  ORDER BY effective_at DESC, source_sequence DESC\n)=1;',output:'Customers: 2,418,221\nDuplicate customer keys: 0\nPASS.'},
      {title:'Top 3 per department',level:'Core',prompt:'Return the top three salary ranks per department while preserving ties.',starter:'SELECT department_id, employee_id, salary FROM employee;',criteria:[['Ranking window',/dense_rank\s*\(|rank\s*\(/i],['Partition by department',/partition\s+by\s+department_id/i],['Salary descending',/order\s+by\s+salary\s+desc/i],['Top three filter',/<=\s*3|between\s+1\s+and\s+3/i]],reference:'WITH r AS (\n SELECT *, DENSE_RANK() OVER(\n   PARTITION BY department_id ORDER BY salary DESC\n ) AS salary_rank\n FROM employee\n)\nSELECT * FROM r WHERE salary_rank<=3;',output:'PASS: top 3 ranking positions retained per department.'},
      {title:'Running loyalty balance',level:'Core',prompt:'Calculate a running points balance by customer ordered by event time and sequence.',starter:'SELECT customer_id,event_time,points_delta FROM loyalty_ledger;',criteria:[['SUM window',/sum\s*\(\s*points_delta\s*\)\s+over/i],['Partition customer',/partition\s+by\s+customer_id/i],['Ordered window',/order\s+by[\s\S]*event_time/i]],reference:'SELECT customer_id,event_time,points_delta,\n SUM(points_delta) OVER(\n   PARTITION BY customer_id\n   ORDER BY event_time,event_sequence\n   ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n ) AS running_balance\nFROM loyalty_ledger;',output:'PASS: balances reproduce ledger ending totals.'},
      {title:'7-day rolling average',level:'Core',prompt:'Compute a seven-day rolling average of daily revenue by property.',starter:'SELECT property_id,business_date,revenue FROM property_daily;',criteria:[['AVG window',/avg\s*\(\s*revenue\s*\)\s+over/i],['Partition property',/partition\s+by\s+property_id/i],['Seven row frame',/rows\s+between\s+6\s+preceding\s+and\s+current\s+row/i]],reference:'SELECT property_id,business_date,revenue,\n AVG(revenue) OVER(\n  PARTITION BY property_id ORDER BY business_date\n  ROWS BETWEEN 6 PRECEDING AND CURRENT ROW\n ) AS revenue_7d_avg\nFROM property_daily;',output:'PASS: rolling window uses current day plus six prior days.'},
      {title:'Month-over-month growth',level:'Core',prompt:'Calculate month-over-month revenue growth after monthly aggregation.',starter:'SELECT DATE_TRUNC(month,event_date) month,revenue FROM sale;',criteria:[['Monthly aggregation',/date_trunc\s*\(|group\s+by/i],['LAG prior month',/lag\s*\(/i],['Growth math',/revenue[\s\S]*-[\s\S]*prev|prev[\s\S]*revenue|\/\s*(prev|lag)/i]],reference:'WITH m AS (\n SELECT DATE_TRUNC(\'month\',event_date) month,SUM(revenue) revenue\n FROM sale GROUP BY 1\n), x AS (\n SELECT *,LAG(revenue) OVER(ORDER BY month) prev_revenue FROM m\n)\nSELECT *, (revenue-prev_revenue)/NULLIF(prev_revenue,0) AS mom_growth\nFROM x;',output:'PASS: monthly grain established before LAG.'},
      {title:'Full outer reconciliation',level:'Senior',prompt:'Classify source-only, target-only, amount mismatch, and match by business_id.',starter:'SELECT * FROM source s JOIN target t ON s.business_id=t.business_id;',criteria:[['FULL OUTER JOIN',/full\s+outer\s+join/i],['Coalesced key',/coalesce\s*\(/i],['Mismatch classification',/case[\s\S]*(source_only|target_only|amount_mismatch|mismatch)/i]],reference:'SELECT COALESCE(s.business_id,t.business_id) business_id,\n CASE WHEN s.business_id IS NULL THEN \'TARGET_ONLY\'\n      WHEN t.business_id IS NULL THEN \'SOURCE_ONLY\'\n      WHEN s.amount<>t.amount THEN \'AMOUNT_MISMATCH\'\n      ELSE \'MATCH\' END status\nFROM source s FULL OUTER JOIN target t\n ON s.business_id=t.business_id;',output:'SOURCE_ONLY 12\nTARGET_ONLY 7\nAMOUNT_MISMATCH 3\nMATCH 499,978\nResidual must be explained before publication.'},
      {title:'SCD2 point-in-time join',level:'Senior',prompt:'Join each fact to the customer tier that was valid at fact.event_time.',starter:'SELECT * FROM fact_event f JOIN dim_customer d ON f.customer_id=d.customer_id;',criteria:[['Business key join',/f\.customer_id\s*=\s*d\.customer_id/i],['Effective-from bound',/event_time\s*>=\s*d\.(effective_from|valid_from)/i],['Effective-to bound',/event_time\s*<\s*d\.(effective_to|valid_to)|event_time\s*<=\s*d\.(effective_to|valid_to)/i]],reference:'SELECT f.*,d.tier\nFROM fact_event f\nJOIN dim_customer d\n ON f.customer_id=d.customer_id\nAND f.event_time>=d.effective_from\nAND f.event_time<d.effective_to;',output:'PASS: historical facts use as-of customer state; no current-state rewrite.'},
      {title:'Snowflake VARIANT + FLATTEN',level:'Senior',prompt:'Explode the items array from raw_event.payload and return sku and quantity.',starter:'SELECT payload FROM raw_event;',criteria:[['LATERAL FLATTEN',/lateral\s+flatten|flatten\s*\(/i],['Items input path',/payload[\s\S]*items|input\s*=>/i],['Variant field extraction',/value[\s\S]*sku|:\s*sku/i]],reference:'SELECT r.event_id, f.value:sku::STRING sku, f.value:quantity::NUMBER qty\nFROM raw_event r,\nLATERAL FLATTEN(input=>r.payload:items) f;',output:'PASS: nested items exploded without losing event identity.'},
      {title:'Idempotent MERGE',level:'Senior',prompt:'Upsert reward events so replay cannot create a second reward and older sequences cannot regress state.',starter:'INSERT INTO reward SELECT * FROM updates;',criteria:[['MERGE statement',/merge\s+into/i],['Deterministic business key',/reward_id|event_id/i],['Sequence guard',/sequence[\s\S]*>|>[\s\S]*sequence/i],['Insert unmatched',/when\s+not\s+matched/i]],reference:'MERGE INTO reward t USING updates s\nON t.reward_id=s.reward_id\nWHEN MATCHED AND s.event_sequence>t.event_sequence THEN UPDATE SET status=s.status,event_sequence=s.event_sequence\nWHEN NOT MATCHED THEN INSERT (reward_id,status,event_sequence) VALUES(s.reward_id,s.status,s.event_sequence);',output:'Replay test: 50,000 input events → 50,000 reward keys\nDuplicate business effects: 0\nPASS.'},
      {title:'Bounded incremental watermark',level:'Senior',prompt:'Extract rows after the previous committed watermark and up to the current high-water mark.',starter:'SELECT * FROM source_table;',criteria:[['Lower exclusive bound',/>\s*:?previous|>\s*\$\{?previous|source_updated_at\s*>/i],['Upper inclusive bound',/<=\s*:?current|<=\s*\$\{?current|source_updated_at\s*<=/i]],reference:'SELECT * FROM source_table\nWHERE source_updated_at > :previous_watermark\n  AND source_updated_at <= :current_high_watermark;',output:'PASS: restartable extraction interval has no overlap gap.'},
      {title:'Pruning-safe date filter',level:'Senior',prompt:'Rewrite a one-day timestamp filter so Snowflake can prune effectively.',starter:"SELECT * FROM fact_event WHERE TO_DATE(event_ts)='2026-08-07';",criteria:[['Native lower range',/event_ts\s*>=/i],['Native upper range',/event_ts\s*</i]],forbidden:[['Avoid wrapping filter column',/to_date\s*\(\s*event_ts/i]],reference:"SELECT * FROM fact_event\nWHERE event_ts >= '2026-08-07'::TIMESTAMP\n  AND event_ts <  '2026-08-08'::TIMESTAMP;",output:'Before: 24.1 TB scanned / 0.59% pruning\nAfter: 181 GB / 99.25% pruning\nPASS.'},
      {title:'Gaps and islands sessions',level:'Principal',prompt:'Create a new session when the gap between customer events exceeds 30 minutes.',starter:'SELECT customer_id,event_time FROM event;',criteria:[['LAG previous event',/lag\s*\(\s*event_time/i],['Thirty minute gap',/30\s*minute|datediff|dateadd/i],['Cumulative session id',/sum\s*\([\s\S]*over/i]],reference:'WITH x AS (\n SELECT *,LAG(event_time) OVER(PARTITION BY customer_id ORDER BY event_time) prev_time\n FROM event\n), y AS (\n SELECT *,IFF(prev_time IS NULL OR DATEDIFF(minute,prev_time,event_time)>30,1,0) new_session\n FROM x\n)\nSELECT *,SUM(new_session) OVER(PARTITION BY customer_id ORDER BY event_time) session_id FROM y;',output:'PASS: sessions are deterministic at customer/event-time grain.'},
      {title:'Conditional business controls',level:'Principal',prompt:'Produce accepted, rejected, duplicate counts and accepted amount in one grouped control query.',starter:'SELECT COUNT(*) FROM batch_event;',criteria:[['Conditional aggregation',/sum\s*\(\s*case|count_if\s*\(/i],['Accepted control',/accepted/i],['Rejected control',/rejected/i],['Duplicate control',/duplicate/i],['Amount control',/amount/i]],reference:'SELECT batch_id,\n COUNT_IF(status=\'ACCEPTED\') accepted_count,\n COUNT_IF(status=\'REJECTED\') rejected_count,\n COUNT_IF(status=\'DUPLICATE\') duplicate_count,\n SUM(IFF(status=\'ACCEPTED\',amount,0)) accepted_amount\nFROM batch_event GROUP BY batch_id;',output:'PASS: control totals generated at batch grain.'}
    ],
    PySpark:[
      {title:'Explicit JSON schema',level:'Core',prompt:'Parse raw JSON using an explicit schema rather than inference.',starter:'df = spark.read.json(path)',criteria:[['StructType schema',/StructType|StructField/i],['Apply schema',/schema\s*\(|from_json\s*\(/i]],reference:'schema = StructType([StructField("event_id",StringType(),False),StructField("amount",DecimalType(18,2),True)])\ndf = spark.read.schema(schema).json(path)',output:'PASS: schema is deterministic and reviewable.'},
      {title:'Explode nested items',level:'Core',prompt:'Explode payload.items while retaining event_id.',starter:'df.select("event_id","payload.items")',criteria:[['explode function',/explode(_outer)?\s*\(/i],['Retain event id',/event_id/i],['Select nested item fields',/item|sku|quantity/i]],reference:'items = df.select("event_id", F.explode_outer("payload.items").alias("item"))\nresult = items.select("event_id","item.sku","item.quantity")',output:'PASS: one row per event item; parent identity retained.'},
      {title:'Latest row with Window',level:'Core',prompt:'Keep the newest customer row using updated_at and source_sequence.',starter:'latest = df.dropDuplicates(["customer_id"])',criteria:[['Window partition',/Window\.partitionBy\s*\(\s*["\']customer_id/i],['Descending ordering',/orderBy[\s\S]*desc/i],['row_number',/row_number\s*\(/i],['Filter rank one',/==\s*1|=\s*1/i]],reference:'w=Window.partitionBy("customer_id").orderBy(F.col("updated_at").desc(),F.col("source_sequence").desc())\nlatest=df.withColumn("rn",F.row_number().over(w)).filter(F.col("rn")==1).drop("rn")',output:'PASS: deterministic latest row per customer.'},
      {title:'Streaming watermark + dedupe',level:'Senior',prompt:'Bound state and deduplicate by source_system + event_id.',starter:'clean = stream.dropDuplicates(["event_id"])',criteria:[['Watermark',/withWatermark\s*\(/i],['Event-time column',/event_time/i],['Composite dedupe key',/source_system[\s\S]*event_id|event_id[\s\S]*source_system/i]],reference:'clean=(stream.withWatermark("event_time","20 minutes").dropDuplicates(["source_system","event_id"]))',output:'State rows stabilize; replay-safe dedupe key present\nPASS.'},
      {title:'Grouped business aggregate',level:'Core',prompt:'Calculate total qualifying points and event count by customer.',starter:'result = df.collect()',criteria:[['groupBy customer',/groupBy\s*\(["\']customer_id/i],['sum points',/sum\s*\(["\']qualifying_points|F\.sum/i],['count events',/count\s*\(|F\.count/i]],forbidden:[['Do not collect large data',/\.collect\s*\(/i]],reference:'result=(df.groupBy("customer_id").agg(F.sum("qualifying_points").alias("points"),F.count("*").alias("event_count")))',output:'PASS: aggregation stays distributed.'},
      {title:'Left anti join',level:'Core',prompt:'Return customers with no matching redemption records.',starter:'customers.join(redemptions,"customer_id")',criteria:[['left_anti join',/left_anti|leftanti/i],['customer key',/customer_id/i]],reference:'never_redeemed = customers.join(redemptions.select("customer_id").distinct(),"customer_id","left_anti")',output:'PASS: anti population returned without null-filter ambiguity.'},
      {title:'Conditional transformation',level:'Core',prompt:'Create quality_status: REJECTED for null event_id, QUARANTINE for invalid amount, otherwise ACCEPTED.',starter:'df.withColumn("quality_status", F.lit("ACCEPTED"))',criteria:[['when logic',/F\.when|when\s*\(/i],['Null event id rule',/event_id[\s\S]*(isNull|null)/i],['Invalid amount rule',/amount/i],['otherwise accepted',/otherwise\s*\(["\']ACCEPTED/i]],reference:'out=df.withColumn("quality_status",F.when(F.col("event_id").isNull(),"REJECTED").when(F.col("amount").isNull(),"QUARANTINE").otherwise("ACCEPTED"))',output:'PASS: every record receives an explicit quality classification.'},
      {title:'Broadcast a genuinely small dimension',level:'Senior',prompt:'Join a 25 MB static reward-rule dimension to a 2 TB event fact efficiently.',starter:'result = fact.join(rule_dim,"rule_id")',criteria:[['broadcast hint',/broadcast\s*\(/i],['Business join key',/rule_id/i]],reference:'result=fact.join(F.broadcast(rule_dim),"rule_id","left")',output:'PASS under stated 25 MB dimension assumption. Re-measure size/volatility before using in production.'},
      {title:'Repartition for parallel write',level:'Senior',prompt:'Prepare a 3 TB table for a large keyed join/write without collapsing to four partitions.',starter:'silver = silver.repartition(4)',criteria:[['Repartition by key or adaptive approach',/repartition\s*\([\s\S]*(customer_id|property_id)|adaptive/i]],forbidden:[['Reject arbitrary four partitions',/repartition\s*\(\s*4\s*\)/i],['Reject single partition',/coalesce\s*\(\s*1\s*\)/i]],reference:'spark.conf.set("spark.sql.adaptive.enabled","true")\nsilver = silver.repartition("customer_id")',output:'PASS: no artificial low-parallelism bottleneck.'},
      {title:'foreachBatch idempotent sink',level:'Senior',prompt:'Use foreachBatch to MERGE each streaming batch by reward_id.',starter:'stream.writeStream.format("delta").outputMode("append")',criteria:[['foreachBatch',/foreachBatch/i],['MERGE operation',/merge/i],['reward id key',/reward_id/i]],reference:'def upsert(batch_df,batch_id):\n  target=DeltaTable.forName(spark,"gold.reward")\n  (target.alias("t").merge(batch_df.alias("s"),"t.reward_id=s.reward_id").whenNotMatchedInsertAll().execute())\n\nstream.writeStream.foreachBatch(upsert).option("checkpointLocation",checkpoint).start()',output:'Replay same batch twice → target reward keys unchanged\nPASS.'},
      {title:'Rolling customer window',level:'Senior',prompt:'Compute rolling seven-row average spend per customer ordered by business_date.',starter:'df.withColumn("avg", F.avg("spend"))',criteria:[['Window partition',/Window\.partitionBy[\s\S]*customer_id/i],['Order by date',/orderBy[\s\S]*business_date/i],['rowsBetween -6 to current',/rowsBetween\s*\(\s*-?6\s*,\s*0\s*\)/i],['avg over window',/avg\s*\([\s\S]*\.over/i]],reference:'w=Window.partitionBy("customer_id").orderBy("business_date").rowsBetween(-6,0)\nout=df.withColumn("spend_7d_avg",F.avg("spend").over(w))',output:'PASS: deterministic row-frame rolling metric.'},
      {title:'Parse and quarantine corrupt JSON',level:'Principal',prompt:'Parse raw payload with from_json and route unparseable records to quarantine instead of dropping them.',starter:'parsed = raw.select(F.from_json("payload", schema).alias("x")).dropna()',criteria:[['from_json parse',/from_json\s*\(/i],['Detect null parse',/isNull\s*\(|_corrupt|parse_error/i],['Quarantine branch',/quarantine|bad_records|reject/i]],forbidden:[['Do not silently drop bad rows',/dropna\s*\(/i]],reference:'parsed=raw.withColumn("parsed",F.from_json("payload",schema))\nquarantine=parsed.filter(F.col("parsed").isNull())\naccepted=parsed.filter(F.col("parsed").isNotNull()).select("parsed.*")',output:'PASS: raw evidence retained and malformed events classified.'}
    ],
    Tests:[
      {title:'pytest parameterized reward rules',level:'Core',prompt:'Write parameterized tests for points: 100 at multiplier 2 = 200; zero spend = zero; negative spend rejected.',starter:'def test_points():\n    assert calculate_points(100,2)==200',criteria:[['pytest parametrize',/pytest\.mark\.parametrize/i],['Multiple cases',/100|200[\s\S]*0/i],['Negative/exception case',/raises\s*\(|negative|ValueError/i]],reference:'@pytest.mark.parametrize("spend,multiplier,expected",[(100,2,200),(0,2,0)])\ndef test_points(spend,multiplier,expected):\n    assert calculate_points(spend,multiplier)==expected\n\ndef test_negative_spend():\n    with pytest.raises(ValueError): calculate_points(-1,2)',output:'3 tests passed\nPASS: happy path + boundary + invalid input.'},
      {title:'PySpark DataFrame unit test',level:'Senior',prompt:'Test a transformation with a tiny input DataFrame and assert the exact expected DataFrame.',starter:'def test_transform(spark):\n    result=transform(None)',criteria:[['Create input DataFrame',/createDataFrame/i],['Expected DataFrame',/expected/i],['DataFrame equality assertion',/assertDataFrameEqual|collect\s*\(\)[\s\S]*==/i]],reference:'from pyspark.testing.utils import assertDataFrameEqual\ndef test_transform(spark):\n    src=spark.createDataFrame([(1,10.0)],"customer_id int, amount double")\n    expected=spark.createDataFrame([(1,20.0)],"customer_id int, points double")\n    assertDataFrameEqual(transform(src),expected)',output:'1 passed\nSchema + row values match.'},
      {title:'Mock API timeout',level:'Senior',prompt:'Unit-test that an upstream timeout is converted to the approved retryable exception without making a real HTTP call.',starter:'def test_api():\n    call_partner_api()',criteria:[['Mock/monkeypatch',/monkeypatch|mock\.patch|patch\s*\(/i],['Timeout exception',/Timeout|timeout/i],['Assert raised/handled',/raises\s*\(|assert/i]],reference:'def test_timeout(monkeypatch):\n    def boom(*a,**k): raise requests.Timeout()\n    monkeypatch.setattr(requests,"get",boom)\n    with pytest.raises(RetryablePartnerError): call_partner_api()',output:'No network call made\nRetryable error mapping PASS.'},
      {title:'Retry 429 then succeed',level:'Senior',prompt:'Test two HTTP 429 responses followed by 200 and assert exactly three attempts.',starter:'def test_retry(): pass',criteria:[['Sequence side effect',/side_effect|iter\s*\(|responses/i],['429 present',/429/i],['200 present',/200/i],['Assert call count three',/call_count\s*==\s*3|assert[\s\S]*3/i]],reference:'mock_get.side_effect=[resp(429),resp(429),resp(200,{"ok":True})]\nassert client.fetch()["ok"] is True\nassert mock_get.call_count==3',output:'Attempts: 3\nFinal status: 200\nPASS.'},
      {title:'Idempotency regression test',level:'Senior',prompt:'Call the same reward event twice and prove only one business effect exists.',starter:'def test_reward(): process(event)',criteria:[['Process same event twice',/process\s*\([\s\S]*process\s*\(/i],['Assert one effect',/==\s*1|count\s*\([\s\S]*1/i],['Deterministic key',/reward_id|event_id/i]],reference:'def test_idempotent_reward(repo,event):\n    process(event,repo); process(event,repo)\n    assert repo.count_by_reward_id(event.reward_id)==1',output:'Input attempts: 2\nBusiness effects: 1\nPASS.'},
      {title:'Schema validator rejects breaking type',level:'Senior',prompt:'Test that DECIMAL→VARCHAR on financial amount is detected as a breaking schema change.',starter:'def test_schema(): assert validate(old,new)',criteria:[['Old/new schemas',/old|previous[\s\S]*new|current/i],['amount field',/amount/i],['Assert breaking/failure',/raises\s*\(|assert[\s\S]*(False|breaking|incompatible)/i]],reference:'def test_breaking_amount_type():\n    old={"amount":"DECIMAL(18,2)"}; new={"amount":"VARCHAR"}\n    with pytest.raises(BreakingSchemaChange): validate_compatibility(old,new)',output:'BreakingSchemaChange raised\nPASS.'},
      {title:'Control-total invariant test',level:'Principal',prompt:'Test source_count = accepted + rejected + duplicates + late.',starter:'def test_controls(c): pass',criteria:[['Source count',/source_count/i],['All classifications',/accepted[\s\S]*rejected[\s\S]*duplicate[\s\S]*late|late[\s\S]*duplicate[\s\S]*rejected[\s\S]*accepted/i],['Equality assertion',/assert[\s\S]*==/i]],reference:'def test_control_equation(c):\n    classified=c.accepted+c.rejected+c.duplicates+c.late\n    assert c.source_count==classified',output:'Control equation PASS.'},
      {title:'API response contract test',level:'Principal',prompt:'Assert scoring response contains score, model_version, feature_timestamp, request_id and a bounded score.',starter:'def test_score(client):\n    r=client.post("/score",json={})',criteria:[['HTTP success assertion',/status_code\s*==\s*200/i],['Required fields',/score[\s\S]*model_version[\s\S]*feature_timestamp[\s\S]*request_id/i],['Score bounds',/0[\s\S]*<=|between|<=\s*1/i]],reference:'def test_score_contract(client,payload):\n    r=client.post("/score",json=payload)\n    assert r.status_code==200\n    body=r.json()\n    for k in ["score","model_version","feature_timestamp","request_id"]: assert k in body\n    assert 0<=body["score"]<=1',output:'Contract fields PASS\nScore bounds PASS.'}
    ],
    dbt:[
      {title:'Staging model contract',level:'Core',prompt:'Build a staging model from source() with renamed/cast fields and no business aggregation.',starter:'SELECT * FROM raw.loyalty_event',criteria:[['source() usage',/source\s*\(/i],['Explicit select/casts',/cast\s*\(|::/i],['Stable renamed fields',/event_id|customer_id/i]],reference:"SELECT\n event_id::STRING AS event_id,\n customer_id::STRING AS customer_id,\n event_ts::TIMESTAMP AS event_ts\nFROM {{ source('loyalty','event') }}",output:'dbt compile PASS\nStaging grain preserved.'},
      {title:'Incremental model with lookback',level:'Senior',prompt:'Configure an incremental model with unique_key event_id and a six-hour late-arrival lookback.',starter:'{{ config(materialized="table") }}\nSELECT * FROM {{ ref("stg_event") }}',criteria:[['Incremental materialization',/materialized["\']?\s*[:=]\s*["\']incremental/i],['unique_key',/unique_key[\s\S]*event_id/i],['is_incremental block',/is_incremental\s*\(/i],['Six-hour lookback',/dateadd[\s\S]*hour[\s\S]*-6|-6[\s\S]*hour/i]],reference:"{{ config(materialized='incremental',unique_key='event_id') }}\nSELECT * FROM {{ ref('stg_event') }}\n{% if is_incremental() %}\nWHERE event_ts >= DATEADD(hour,-6,(SELECT MAX(event_ts) FROM {{ this }}))\n{% endif %}",output:'dbt build PASS\nLate-arrival replay remains idempotent.'},
      {title:'Schema tests',level:'Core',prompt:'Define not_null and unique on event_id and relationships from customer_id to dim_customer.',starter:'version: 2\nmodels: []',criteria:[['not_null',/not_null/i],['unique',/unique/i],['relationships',/relationships/i],['customer relation',/customer_id[\s\S]*dim_customer|ref[\s\S]*dim_customer/i]],reference:'version: 2\nmodels:\n - name: fct_event\n   columns:\n    - name: event_id\n      tests: [not_null, unique]\n    - name: customer_id\n      tests:\n       - relationships:\n           to: ref(\'dim_customer\')\n           field: customer_id',output:'3 generic tests PASS.'},
      {title:'Source freshness',level:'Core',prompt:'Require warning after 10 minutes and error after 20 minutes of source staleness.',starter:'sources:\n - name: loyalty',criteria:[['freshness block',/freshness/i],['Warn 10 minutes',/warn_after[\s\S]*10[\s\S]*minute/i],['Error 20 minutes',/error_after[\s\S]*20[\s\S]*minute/i],['loaded_at field',/loaded_at_field/i]],reference:"sources:\n- name: loyalty\n  loaded_at_field: _loaded_at\n  freshness:\n    warn_after: {count: 10, period: minute}\n    error_after: {count: 20, period: minute}",output:'Source freshness contract PASS.'},
      {title:'Singular reconciliation test',level:'Senior',prompt:'Write a singular test that returns rows only when source and target daily amount totals differ.',starter:'SELECT 1',criteria:[['Aggregate source',/sum\s*\([\s\S]*source|source[\s\S]*sum\s*\(/i],['Aggregate target',/sum\s*\([\s\S]*target|target[\s\S]*sum\s*\(/i],['Mismatch filter',/<>|!=|abs\s*\(/i]],reference:'WITH s AS (SELECT business_date,SUM(amount) amt FROM {{ ref(\'stg_sale\') }} GROUP BY 1),\nt AS (SELECT business_date,SUM(amount) amt FROM {{ ref(\'fct_sale\') }} GROUP BY 1)\nSELECT COALESCE(s.business_date,t.business_date) business_date\nFROM s FULL OUTER JOIN t USING(business_date)\nWHERE COALESCE(s.amt,0)<>COALESCE(t.amt,0)',output:'0 rows returned = PASS.'},
      {title:'safe_divide macro',level:'Senior',prompt:'Create a Jinja macro that returns null when denominator is zero/null and otherwise divides.',starter:'{% macro safe_divide(a,b) %}\n{{ a / b }}\n{% endmacro %}',criteria:[['macro declaration',/macro\s+safe_divide/i],['Zero/null protection',/nullif|case|iff/i],['Division',/\//i]],reference:'{% macro safe_divide(numerator, denominator) %}\n  ({{ numerator }}) / NULLIF(({{ denominator }}),0)\n{% endmacro %}',output:'Macro compile PASS\nZero denominator returns NULL.'},
      {title:'SCD2 snapshot',level:'Senior',prompt:'Configure a timestamp-strategy snapshot for customer records keyed by customer_id and updated_at.',starter:'{% snapshot customer_snapshot %}{% endsnapshot %}',criteria:[['snapshot config',/snapshot[\s\S]*config/i],['unique key customer',/unique_key[\s\S]*customer_id/i],['timestamp strategy',/strategy[\s\S]*timestamp/i],['updated_at',/updated_at/i]],reference:"{% snapshot customer_snapshot %}\n{{ config(target_schema='snapshots',unique_key='customer_id',strategy='timestamp',updated_at='updated_at') }}\nSELECT * FROM {{ source('crm','customer') }}\n{% endsnapshot %}",output:'Snapshot config PASS\nHistorical changes preserved.'},
      {title:'Semantic metric contract',level:'Principal',prompt:'Define governed net_revenue with an owner, formula, grain/time dimension and description of returns/discounts.',starter:'metrics:\n - name: net_revenue',criteria:[['Metric name',/net_revenue/i],['Owner metadata',/owner/i],['Time dimension/grain',/time|grain|timestamp/i],['Business formula context',/discount|return|gross|revenue/i]],reference:'semantic_models:\n- name: sales\n  defaults: {agg_time_dimension: business_date}\nmetrics:\n- name: net_revenue\n  type: simple\n  label: Net Revenue\n  description: Gross revenue less approved discounts and returns.\n  meta: {owner: Finance Data Product}',output:'Semantic contract review PASS.'}
    ],
    API:[
      {title:'FastAPI scoring endpoint',level:'Core',prompt:'Create POST /score with a Pydantic request model and response model.',starter:'@app.get("/score")\ndef score(): return model.predict()',criteria:[['POST route',/@app\.post\s*\(["\']\/score/i],['Pydantic BaseModel',/BaseModel/i],['Request type annotation',/def\s+score[\s\S]*:/i],['Response model',/response_model/i]],reference:'class ScoreRequest(BaseModel):\n    customer_id:str\n    amount:float\nclass ScoreResponse(BaseModel):\n    score:float\n    model_version:str\n@app.post("/score",response_model=ScoreResponse)\ndef score(req:ScoreRequest): ...',output:'OpenAPI contract generated\nPOST /score PASS.'},
      {title:'Scoring provenance',level:'Senior',prompt:'Return score plus model_version, feature_timestamp, request_id and decision_timestamp.',starter:'return {"score": score}',criteria:[['model version',/model_version/i],['feature timestamp',/feature_timestamp/i],['request id',/request_id/i],['decision timestamp',/decision_timestamp/i]],reference:'return ScoreResponse(score=p,model_version=MODEL_VERSION,feature_timestamp=features.as_of,request_id=request_id,decision_timestamp=datetime.now(timezone.utc))',output:'PASS: prediction is traceable to model and feature state.'},
      {title:'Timeout + bounded retry',level:'Senior',prompt:'Call an upstream service with a timeout and bounded retry for 429/503.',starter:'requests.get(url)',criteria:[['Timeout set',/timeout\s*=/i],['429/503 handling',/429|503/i],['Bounded attempts',/max_attempts|range\s*\(|retry/i],['Backoff',/backoff|sleep\s*\(/i]],reference:'for attempt in range(3):\n r=requests.get(url,timeout=2.0)\n if r.status_code not in (429,503): r.raise_for_status(); return r.json()\n time.sleep(2**attempt)\nraise UpstreamUnavailable()',output:'Retries bounded at 3\nTimeout 2s\nPASS.'},
      {title:'Cursor pagination',level:'Core',prompt:'Fetch every page until next_cursor is null and persist the committed cursor only after batch acceptance.',starter:'data=requests.get(url).json()',criteria:[['Loop pages',/while|for/i],['next_cursor',/next_cursor|cursor/i],['Stop on null/empty',/if[\s\S]*(not|null|none)[\s\S]*cursor|while[\s\S]*cursor/i],['Commit after acceptance',/accept|commit|checkpoint/i]],reference:'cursor=load_committed_cursor()\nwhile True:\n body=fetch(cursor)\n write_staging(body["items"])\n if not body.get("next_cursor"): break\n cursor=body["next_cursor"]\nvalidate_and_accept_batch(); commit_cursor(cursor)',output:'All pages fetched\nCursor commit occurs after acceptance.'},
      {title:'Idempotency key on mutation',level:'Senior',prompt:'Protect POST /redeem so client retries cannot redeem the same reward twice.',starter:'@app.post("/redeem")\ndef redeem(req): db.insert(req)',criteria:[['Idempotency header/key',/idempotency[_-]?key|header/i],['Unique durable lookup',/unique|existing|get_by|select/i],['Return existing result on replay',/return[\s\S]*(existing|prior|current)/i]],reference:'@app.post("/redeem")\ndef redeem(req:RedeemRequest,idempotency_key:str=Header(...)):\n existing=repo.get_by_idempotency_key(idempotency_key)\n if existing: return existing\n return repo.create_atomic(req,idempotency_key)',output:'Replay request returns original redemption\nBusiness effects: 1\nPASS.'},
      {title:'Batch scoring endpoint',level:'Senior',prompt:'Design POST /score/batch with a bounded request size and per-item results/errors.',starter:'@app.post("/score/batch")\ndef batch(items:list): return [model(x) for x in items]',criteria:[['POST batch route',/@app\.post[\s\S]*score\/batch/i],['Bound request size',/max_|len\s*\(|conlist|1000|limit/i],['Per-item result/error',/error|status|result/i]],reference:'class BatchRequest(BaseModel): items: conlist(ScoreRequest,min_length=1,max_length=1000)\n@app.post("/score/batch")\ndef batch(req:BatchRequest): return {"results":[score_one(x) for x in req.items]}',output:'1000-item max enforced\nPer-item traceability PASS.'},
      {title:'Least-privilege analytics API',level:'Principal',prompt:'Restrict generated analytics SQL to SELECT against allowlisted semantic views with row/time limits.',starter:'sql=llm(prompt); return admin_db.execute(sql)',criteria:[['SELECT-only validation',/select.only|startswith\s*\(["\']select|parse/i],['Allowlist views',/allowlist|allowed_views|semantic/i],['Row limit',/limit|max_rows/i],['Timeout',/timeout/i]],forbidden:[['No admin execution',/admin_db|accountadmin/i]],reference:'assert parsed.statement_type=="SELECT"\nassert parsed.tables <= ALLOWED_SEMANTIC_VIEWS\nsql=enforce_limit(sql,1000)\nreturn readonly_db.execute(sql,timeout=5)',output:'Authorization boundary PASS\nDestructive SQL rejected.'},
      {title:'API SLO instrumentation',level:'Principal',prompt:'Instrument request count, errors and latency; calculate/emit p95 latency and model-version labels.',starter:'def score(req): return predict(req)',criteria:[['Latency timing',/time\.|perf_counter|latency/i],['Request/error counters',/counter|requests_total|errors_total/i],['Histogram/p95',/histogram|p95|percentile/i],['Model version label',/model_version/i]],reference:'with SCORE_LATENCY.labels(model_version=MODEL_VERSION).time():\n  SCORE_REQUESTS.labels(model_version=MODEL_VERSION).inc()\n  return predict(req)\n# alert on p95 and error-rate SLOs',output:'Metrics emitted: request rate, errors, latency histogram, model version\nPASS.'}
    ],
    Dev:[
      {title:'Pre-merge quality gate',level:'Core',prompt:'Define CI steps for Python lint, unit tests, dbt compile/test and a build artifact before merge.',starter:'steps:\n - run: echo deploy',criteria:[['Python lint',/ruff|flake8|pylint/i],['pytest',/pytest/i],['dbt compile/build/test',/dbt\s+(compile|build|test)/i],['Artifact/build',/artifact|build/i]],reference:'steps:\n - run: ruff check .\n - run: pytest -q\n - run: dbt deps && dbt build --target ci\n - uses: actions/upload-artifact@v4',output:'CI gate PASS: lint + tests + dbt + artifact.'},
      {title:'Secrets through environment',level:'Core',prompt:'Remove a hard-coded Snowflake password from code and load it securely.',starter:'SNOWFLAKE_PASSWORD="SuperSecret123"',criteria:[['Environment/secret manager',/os\.environ|getenv|secret|vault|key_vault/i]],forbidden:[['No literal secret',/SuperSecret123/i]],reference:'SNOWFLAKE_PASSWORD=os.environ["SNOWFLAKE_PASSWORD"]\n# value injected by approved secret manager',output:'Secret scan PASS\nNo credential literal committed.'},
      {title:'Canary deployment gate',level:'Senior',prompt:'Deploy a small canary, run smoke + data quality + reconciliation, then promote or rollback.',starter:'deploy_production()',criteria:[['Canary',/canary/i],['Smoke tests',/smoke/i],['Quality/reconciliation',/quality|reconcil/i],['Promote/rollback decision',/promote|rollback/i]],reference:'deploy_canary(percent=5)\nif smoke() and quality() and reconcile(): promote()\nelse: rollback_canary()',output:'PASS: production promotion depends on canary acceptance.'},
      {title:'Rollback when data acceptance fails',level:'Senior',prompt:'Code deployment is green but duplicate rewards and a $62K residual appear. Encode the release gate.',starter:'if deploy_success: publish()',criteria:[['Deployment gate',/deploy/i],['Quality/reconciliation gate',/quality|reconcil/i],['Rollback/block',/rollback|block|freeze/i],['Publish only on all pass',/publish/i]],reference:'if deploy_success and smoke_pass and quality_pass and reconciliation_pass:\n    publish()\nelse:\n    block_publication(); rollback_if_causal()',output:'PASS: deployment success separated from trusted publication.'},
      {title:'Feature flag risky business rule',level:'Senior',prompt:'Ship a new loyalty multiplier behind a reversible feature flag and retain old behavior.',starter:'multiplier=NEW_MULTIPLIER',criteria:[['Feature flag',/feature_flag|flag|enabled/i],['Old fallback',/old|previous|default/i],['New behavior',/new|multiplier/i]],reference:'multiplier = NEW_MULTIPLIER if flags.enabled("loyalty_multiplier_v2",customer_id) else OLD_MULTIPLIER',output:'PASS: rule can be disabled without redeploy.'},
      {title:'Bounded migration/backfill',level:'Principal',prompt:'Build a development guard that requires start/end interval, dry-run changed keys and approved blast radius before execution.',starter:'backfill(all_history=True)',criteria:[['Start/end bounds',/start|from_date[\s\S]*end|to_date/i],['Dry run',/dry_run|dry run/i],['Changed keys/blast radius',/changed_keys|blast_radius|row_count/i],['Approval/threshold',/approve|threshold|max_/i]],reference:'plan=backfill_plan(start,end,dry_run=True)\nassert plan.changed_keys<=APPROVED_BLAST_RADIUS\napprove(plan)\nexecute_backfill(start,end,idempotent=True)',output:'PASS: migration scope and expected effect known before write.'},
      {title:'Post-deploy observability',level:'Senior',prompt:'After release, verify freshness, duplicates, residual, API p95 and cost before closing change.',starter:'deploy(); mark_success()',criteria:[['Freshness',/freshness/i],['Duplicates',/duplicate/i],['Residual/reconciliation',/residual|reconcil/i],['API p95/latency',/p95|latency/i],['Cost',/cost|credit/i]],reference:'deploy(); assert freshness<5*MINUTE; assert duplicate_rewards==0; assert residual==0; assert api_p95<250; assert cost_per_event<=budget; close_change()',output:'PASS: post-deploy acceptance includes technical + business telemetry.'},
      {title:'Development definition of done',level:'Principal',prompt:'Define DoD for a production data change: code, tests, docs, lineage, security, rollback, metrics, runbook and owner.',starter:'Definition of Done: code merged',criteria:[['Tests',/test/i],['Documentation/lineage',/doc|lineage/i],['Security',/security|rbac|secret/i],['Rollback',/rollback/i],['Metrics/observability',/metric|observ/i],['Runbook/owner',/runbook|owner/i]],reference:'DoD = code reviewed; unit/integration/dbt tests pass; lineage/docs updated; security reviewed; rollback tested; SLO/controls instrumented; runbook + owner assigned; post-deploy acceptance passed.',output:'PASS: development completion includes operability.'}
    ]
  };

  const triageCases=[
    {title:'Duplicate rewards actively issuing',sev:'SEV1',impact:'842 duplicate rewards in 7 minutes; customer balance changing.',choices:['Contain reward publication and preserve evidence','Scale Snowflake to 4XL','Restart every service','Wait for the next batch'],answer:0,evidence:'Freeze unsafe publication, preserve checkpoint/offset/query/deploy state, quantify affected reward IDs and ledger residual.'},
    {title:'Production credential exposed in repository',sev:'SEV1',impact:'Admin-like credential committed to public branch.',choices:['Rotate/revoke credential immediately and investigate access','Delete the README only','Wait for next maintenance window','Increase password length later'],answer:0,evidence:'Revoke/rotate, inspect audit access, remove secret/history as required, move to secret manager, scope permissions.'},
    {title:'Kafka lag rising with hot partition',sev:'SEV2',impact:'Lag 1.2M and freshness approaching 5-minute SLA; one partition owns 47%.',choices:['Inspect key distribution and contain downstream risk','Add 20 consumers immediately','Delete checkpoint','Ignore until SLA breach'],answer:0,evidence:'Measure input vs processed, partition skew, consumer ownership, stream batch/state, and sink latency.'},
    {title:'Mobile scoring API p95 = 2.8s',sev:'SEV2',impact:'Checkout personalization timing out; warehouse healthy.',choices:['Inspect API dependency latency, feature retrieval and model path','Increase Kafka retention','Run dbt docs','Full-refresh all marts'],answer:0,evidence:'Trace request latency by dependency, timeout/retry behavior, cache/feature freshness, scoring runtime and error rate.'},
    {title:'dbt docs build failed',sev:'SEV3',impact:'Documentation artifact missing; production models and SLAs healthy.',choices:['Queue after customer/revenue incidents and fix before release close','Declare SEV1 outage','Stop all streaming','Rotate database passwords'],answer:0,evidence:'Confirm no production data effect, record release-quality gap, repair docs/lineage pipeline.'},
    {title:'Fraud queue 15x analyst capacity',sev:'SEV2',impact:'Model now flags 7,500/day; analysts can review 500.',choices:['Assess drift/calibration and contain threshold impact','Send all alerts to analysts','Raise threshold randomly','Delete model registry'],answer:0,evidence:'Check feature/concept drift, calibration, precision at capacity, threshold policy and champion/challenger rollback.'},
    {title:'One Databricks worker auto-recovered',sev:'SEV3',impact:'No data loss, lag unchanged, SLA healthy; infrastructure alert recovered.',choices:['Verify recovery evidence and continue monitoring','Stop customer publication','Backfill all history','Scale cluster 4x'],answer:0,evidence:'Confirm checkpoint continuity, no batch replay anomalies, executor health and lag stability.'},
    {title:'Reconciliation residual $62K after deploy',sev:'SEV1',impact:'CI green but financial mart differs from trusted source.',choices:['Block publication and rollback/isolate causal release','Declare success because CI passed','Disable reconciliation','Increase warehouse size'],answer:0,evidence:'Preserve release SHA/query IDs, classify residual, compare layer controls, rollback if causal, reopen after zero/approved residual.'}
  ];

  function addTab(id,label){
    const b=document.createElement('button'); b.dataset.tab=id; b.textContent=label; nav.appendChild(b);
    b.addEventListener('click',()=>{nav.querySelectorAll('button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');byId(id).classList.add('active')});
  }
  function addSection(id,html){const s=document.createElement('section');s.id=id;s.className='tab';s.innerHTML=html;main.appendChild(s)}

  const scoreStrip=document.createElement('div');scoreStrip.className='advanced-score-strip';scoreStrip.id='advancedScoreStrip';nav.insertAdjacentElement('afterend',scoreStrip);
  const note=document.createElement('div');note.className='advanced-tabs-note';note.textContent='Advanced Mastery V3: code-pattern coverage + simulated execution + rubric scoring. Scores persist locally and feed OpsReady evidence.';scoreStrip.insertAdjacentElement('afterend',note);

  function codeLabHtml(kind){return `<div class="advanced-grid"><div class="advanced-card"><div class="advanced-summary"><div><h2>${kind} Mastery</h2><div class="hint">Choose a pattern and solve it from a blank/starter editor.</div></div><strong id="adv-${kind}-overall">—</strong></div><div id="adv-${kind}-list" class="scenario-list"></div></div><div class="advanced-card"><div class="pattern-meta"><span class="adv-pill" id="adv-${kind}-level">—</span><span class="adv-pill" id="adv-${kind}-coverage">0/${banks[kind].length} attempted</span></div><h2 id="adv-${kind}-title">Select a scenario</h2><p id="adv-${kind}-prompt" class="muted"></p><textarea id="adv-${kind}-editor" class="advanced-editor" spellcheck="false"></textarea><div class="lab-toolbar"><button class="primary" id="adv-${kind}-run">Run / Grade</button><button id="adv-${kind}-reference">Load Reference</button><button id="adv-${kind}-reset">Reset Starter</button></div><pre id="adv-${kind}-output" class="advanced-output">Select a scenario to begin.</pre><div id="adv-${kind}-rubric" class="rubric"></div></div></div>`}

  addTab('advSQL','SQL Patterns'); addSection('advSQL',codeLabHtml('SQL'));
  addTab('advPySpark','PySpark+'); addSection('advPySpark',codeLabHtml('PySpark'));
  addTab('advTests','Python Tests'); addSection('advTests',codeLabHtml('Tests'));
  addTab('advdbt','dbt Dev'); addSection('advdbt',codeLabHtml('dbt'));
  addTab('advAPI','API + Scoring'); addSection('advAPI',codeLabHtml('API'));
  addTab('advDev','Dev & CI/CD'); addSection('advDev',codeLabHtml('Dev'));
  addTab('advTriage','Triage'); addSection('advTriage',`<div class="advanced-grid"><div class="advanced-card"><div class="advanced-summary"><div><h2>Incident Triage Queue</h2><div class="hint">Prioritize by active customer/financial/security impact, blast radius and SLA.</div></div><strong id="adv-Triage-overall">—</strong></div><div id="triageQueue" class="triage-queue"></div></div><div class="advanced-card"><span class="adv-pill" id="triageSev">—</span><h2 id="triageTitle">Select an incident</h2><p id="triageImpact" class="muted"></p><div id="triageChoices"></div><h3>Evidence / triage note</h3><textarea id="triageNote" class="advanced-editor" style="min-height:150px" placeholder="What evidence would you preserve or inspect before destructive recovery?"></textarea><div class="lab-toolbar"><button class="primary" id="gradeTriage">Grade Triage</button></div><pre id="triageOutput" class="advanced-output">Choose an incident and first action.</pre></div></div>`);

  function resultFor(kind,idx){return progress[kind][idx]||null}
  function categoryScore(kind,totalCount){const vals=Object.values(progress[kind]||{}).map(Number).filter(n=>Number.isFinite(n));return {score:vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length):null,attempted:vals.length,total:totalCount}}
  function refreshStrip(){
    scoreStrip.innerHTML='';
    categories.forEach(kind=>{const total=kind==='Triage'?triageCases.length:banks[kind].length;const r=categoryScore(kind,total);const d=document.createElement('div');d.className='adv-score';d.innerHTML=`<span>${kind}</span><b>${r.score===null?'—':r.score+'%'}</b><small>${r.attempted}/${r.total}</small>`;scoreStrip.appendChild(d);const o=byId(`adv-${kind}-overall`);if(o)o.textContent=r.score===null?'—':r.score+'%';});
  }
  function record(kind,idx,score,title,detail){const prev=Number(progress[kind][idx]||0);progress[kind][idx]=Math.max(prev,score);save();refreshStrip();try{if(window.parent!==window)window.parent.postMessage({type:'opsready-lab-score',lab:`${kind}: ${title}`,score,detail},'*');else{let arr=JSON.parse(localStorage.getItem('opsreadyLabEvidence')||'[]');arr.push({lab:`${kind}: ${title}`,score,detail,at:new Date().toISOString()});localStorage.setItem('opsreadyLabEvidence',JSON.stringify(arr.slice(-50)))}}catch(e){}
  }
  function gradeCode(code,scenario){let earned=0,total=scenario.criteria.length*10,rows=[];scenario.criteria.forEach(([label,rx])=>{const ok=rx.test(code);if(ok)earned+=10;rows.push({label,ok})});(scenario.forbidden||[]).forEach(([label,rx])=>{total+=5;const ok=!rx.test(code);if(ok)earned+=5;rows.push({label,ok})});return {score:Math.round(earned/total*100),rows}}

  function initCodeLab(kind){
    const bank=banks[kind],list=byId(`adv-${kind}-list`);let current=0;
    function renderList(){list.innerHTML='';bank.forEach((s,i)=>{const b=document.createElement('button');const best=resultFor(kind,i);b.className='scenario-btn'+(best>=80?' pass':best>0?' partial':'')+(i===current?' active':'');b.innerHTML=`<b>${i+1}. ${esc(s.title)}</b><small>${esc(s.level)}${best?` • best ${best}%`:''}</small>`;b.onclick=()=>{current=i;load();};list.appendChild(b)});const c=categoryScore(kind,bank.length);byId(`adv-${kind}-coverage`).textContent=`${c.attempted}/${c.total} attempted`;}
    function load(){const s=bank[current];byId(`adv-${kind}-title`).textContent=`${current+1}. ${s.title}`;byId(`adv-${kind}-prompt`).textContent=s.prompt;byId(`adv-${kind}-level`).textContent=s.level;byId(`adv-${kind}-editor`).value=s.starter;byId(`adv-${kind}-output`).textContent='Edit the starter, then Run / Grade.';byId(`adv-${kind}-rubric`).innerHTML='';renderList()}
    byId(`adv-${kind}-run`).onclick=()=>{const s=bank[current],code=byId(`adv-${kind}-editor`).value,r=gradeCode(code,s);byId(`adv-${kind}-output`).textContent=`SIMULATED EXECUTION\nScore: ${r.score}%\n\n${r.score>=80?s.output:'Implementation is incomplete. Fix the failed rubric items and run again.'}`;byId(`adv-${kind}-rubric`).innerHTML=r.rows.map(x=>`<div class="rubric-row ${x.ok?'ok':'bad'}"><b>${x.ok?'✓':'✗'}</b><span>${esc(x.label)}</span></div>`).join('');record(kind,current,r.score,s.title,`${r.rows.filter(x=>x.ok).length}/${r.rows.length} rubric checks`);renderList()};
    byId(`adv-${kind}-reference`).onclick=()=>{byId(`adv-${kind}-editor`).value=bank[current].reference;byId(`adv-${kind}-output`).textContent='Reference loaded. Read it, then reset and reproduce it from memory.'};
    byId(`adv-${kind}-reset`).onclick=()=>load();load();
  }
  ['SQL','PySpark','Tests','dbt','API','Dev'].forEach(initCodeLab);

  let triageCurrent=0,triageChoice=null;
  function renderTriage(){const host=byId('triageQueue');host.innerHTML='';triageCases.forEach((t,i)=>{const best=resultFor('Triage',i);const d=document.createElement('div');d.className=`triage-item ${t.sev.toLowerCase()}`;d.innerHTML=`<b>${i+1}. ${esc(t.title)}</b><div class="hint">${t.sev} • ${esc(t.impact)}</div><button>${best?`Review • best ${best}%`:'Triage case'}</button>`;d.querySelector('button').onclick=()=>{triageCurrent=i;triageChoice=null;loadTriage()};host.appendChild(d)});}
  function loadTriage(){const t=triageCases[triageCurrent];byId('triageSev').textContent=t.sev;byId('triageTitle').textContent=t.title;byId('triageImpact').textContent=t.impact;byId('triageNote').value='';byId('triageOutput').textContent='Choose the safest first action, then write what evidence you would preserve/inspect.';const c=byId('triageChoices');c.innerHTML='';t.choices.forEach((x,i)=>{const b=document.createElement('button');b.textContent=x;b.style.display='block';b.style.margin='7px 0';b.onclick=()=>{triageChoice=i;c.querySelectorAll('button').forEach(z=>z.classList.remove('primary'));b.classList.add('primary')};c.appendChild(b)});renderTriage()}
  byId('gradeTriage').onclick=()=>{const t=triageCases[triageCurrent],note=byId('triageNote').value.toLowerCase();let score=triageChoice===t.answer?60:0;const evidenceTerms=['evidence','log','offset','checkpoint','query','audit','impact','count','residual','timeline','metric','preserve','access','drift','latency'];const hits=evidenceTerms.filter(k=>note.includes(k)).length;score+=Math.min(40,hits*8);byId('triageOutput').textContent=`Score: ${score}%\n\nCorrect first action: ${t.choices[t.answer]}\n\nEvidence standard: ${t.evidence}`;record('Triage',triageCurrent,score,t.title,`first action ${triageChoice===t.answer?'correct':'incorrect'}; evidence terms ${hits}`);renderTriage()};
  loadTriage();refreshStrip();
})();