-- Optional GCS landing zone. Do not apply until the storage integration exists.
USE DATABASE ${DATABASE_NAME};
USE SCHEMA BRONZE;

CREATE STAGE IF NOT EXISTS CASINO_GCS_STAGE
  URL = 'gcs://REPLACE_WITH_AUTHORIZED_BUCKET/landing/'
  STORAGE_INTEGRATION = REPLACE_WITH_STORAGE_INTEGRATION
  FILE_FORMAT = JSON_FF
  DIRECTORY = (ENABLE = TRUE AUTO_REFRESH = TRUE);

CREATE PIPE IF NOT EXISTS SLOT_EVENT_FILE_PIPE
  AUTO_INGEST = TRUE
AS
COPY INTO BRONZE.SLOT_EVENTS_RAW (
  RAW_PAYLOAD,
  EVENT_ID,
  EVENT_TIME,
  INGESTION_TIME,
  PROPERTY_ID,
  LOCATION_ID,
  MACHINE_ID,
  EVENT_TYPE,
  AMOUNT,
  CURRENCY,
  SOURCE_SYSTEM,
  SOURCE_FILE,
  SOURCE_ROW_NUMBER,
  SCHEMA_VERSION,
  LOAD_BATCH_ID,
  RECORD_HASH
)
FROM (
  SELECT
    $1,
    $1:event_id::STRING,
    TRY_TO_TIMESTAMP_TZ($1:event_time::STRING),
    CURRENT_TIMESTAMP(),
    $1:property_id::STRING,
    $1:location_id::STRING,
    $1:machine_id::STRING,
    $1:event_type::STRING,
    TRY_TO_DECIMAL($1:amount, 18, 2),
    COALESCE($1:currency::STRING, 'USD'),
    'GCS_FILE',
    METADATA$FILENAME,
    METADATA$FILE_ROW_NUMBER,
    COALESCE($1:schema_version::NUMBER, 1),
    UUID_STRING(),
    SHA2(TO_JSON($1), 256)
  FROM @CASINO_GCS_STAGE/slot_events/
)
ON_ERROR = 'CONTINUE';
