(() => {
const defects=[
['Breaking schema drift on financial amount','7.4% of POS events fail after amount changes DECIMAL → VARCHAR.','Breaking source contract change','amount::NUMBER(18,2)','Quarantine incompatible records, preserve raw, version the schema, normalize approved formats, and reconcile before publication.'],
['Hot partition and lag explosion','One Kafka partition receives 43% because unknown identities use customer_id=GUEST.','Skewed partition key','key = customer_id || "GUEST"','Profile key distribution, use a stable distributed fallback for unknown identities, then right-size partitions/consumers.'],
['Consumer overprovisioning','Topic has 8 partitions but 16 consumers run in the same group.','Consumer count exceeds partition parallelism','replicas: 16','Right-size consumers to available partition parallelism; add partitions only when measured throughput and ordering needs justify it.'],
['Micro-batches exceed trigger interval','Trigger is 60 seconds but average batch duration is 88 seconds.','Processing throughput below arrival rate','.trigger(processingTime="60 seconds")','Decompose source, state, shuffle and sink duration; optimize the constrained stage before adding compute.'],
['Unbounded streaming state','State grows from 18M to 74M rows and executors fail.','Missing watermark on stateful operation','dropDuplicates(["event_id"])','Use event time, a measured watermark, deterministic dedupe keys, and a separate late-correction path.'],
['Driver OOM from collect()','28M events are collected to the driver and looped in Python.','Large distributed dataset collected to driver','rows = df.collect()','Keep transformations distributed using Spark expressions, joins, aggregations or controlled foreachBatch.'],
['Massive shuffle from bad repartition','A 3 TB Silver table is repartitioned to 4 partitions before a join.','Artificially low partition count','silver.repartition(4)','Remove arbitrary tiny partition counts, use AQE, and partition based on actual data size/distribution.'],
['Join explosion in enrichment','12M facts joined to 8M customer rows produce 1.4B output rows.','Many-to-many join from nonunique dimension key','fact.join(dim_customer,"customer_id")','Prove join cardinality; dedupe/current-row or point-in-time SCD logic before enrichment.'],
['Replay creates duplicate rewards','A successful write replays after checkpoint failure and appends 41K rewards twice.','Non-idempotent append sink','mode("append").saveAsTable("gold.reward")','Use deterministic reward/event keys and idempotent MERGE or transactional uniqueness.'],
['Older event overwrites newer state','Stored sequence 17 is overwritten by a late sequence 12 event.','MERGE lacks sequence guard','WHEN MATCHED THEN UPDATE','Collapse source per key and update only when incoming source sequence is newer.'],
['Snowflake query scans 24 TB','One-property one-day query scans nearly the full table.','Poor pruning caused by filter design','WHERE TO_DATE(event_ts)=\'2026-08-07\'','Use native timestamp range predicates, inspect profile, and cluster only after access-pattern evidence.'],
['Warehouse scaling hides join pathology','A larger warehouse makes a query faster but it still produces 700M rows.','Missing or incomplete join predicates','JOIN dim_offer ON property_id','Fix business keys/effective-date predicates and grain before right-sizing compute.'],
['Task backlog from serial orchestration','Eight independent Snowflake transformations are chained serially and miss SLA.','Unnecessary serial task dependencies','A -> B -> C -> D -> E -> F -> G -> H','Model real dependencies and parallelize independent branches while preserving required gates.'],
['Snowflake Stream nearing staleness','A change-tracking Stream is not consumed because its task was disabled for days.','Change-tracking consumer stopped','ALTER TASK reward_consumer SUSPEND','Restore controlled consumption, assess retention/staleness, safely backfill if required, and alert before the boundary.'],
['dbt incremental model misses late events','Strict MAX(event_ts) filtering permanently skips events arriving two hours late.','No incremental lookback/correction window','event_ts > MAX(event_ts)','Use a measured lookback plus deterministic unique_key/MERGE and bounded reprocessing.'],
['Fact table mixes grains','Receipt-level and line-level measures coexist; revenue increases 38%.','Mixed fact grain','receipt_total stored on every receipt line','Declare one grain per fact; separate header/line facts or allocate measures explicitly.'],
['Semantic metric disagreement','Finance reports $8.2M net revenue while Operations reports $8.7M.','Duplicated metric logic with different adjustment rules','custom metric SQL in each dashboard','Create an owned versioned semantic metric with explicit grain, formula, inclusions, exclusions and examples.'],
['Offer API queries analytical warehouse live','Mobile offer p95 becomes 8.4 seconds when Snowflake resumes.','Analytical warehouse used directly as low-latency serving store','GET /offers -> live 2B-row join','Precompute governed eligibility/current state into a compact serving projection/cache.'],
['Stale cache allows redeemed offer','24-hour TTL keeps an already-redeemed reward visible.','Cache invalidation not tied to state changes','CACHE_TTL = 86400','Invalidate on redemption/expiration/compliance events; durable atomic uniqueness remains authoritative.'],
['Idle compute burn','BI warehouse is 82% idle overnight and a Databricks cluster never terminates.','Missing suspend/termination policy','auto_suspend=0; auto_termination=disabled','Use safe auto-suspend/termination and workload isolation while protecting critical SLA paths.'],
['Repeated full-table recomputation','A 6 TB feature table is rebuilt 96 times/day although only 0.2% changes.','No incremental processing strategy','CREATE OR REPLACE from 6TB_history','Use CDC/incremental boundaries and MERGE only changed entities/time windows.'],
['Production credential committed to repo','Snowflake admin password appears in pipeline YAML.','Hard-coded credentials','SNOWFLAKE_PASSWORD: SuperSecret123','Rotate immediately, remove exposure as required, and use secret manager/managed identity with least privilege.'],
['Deployment green but data wrong','CI/CD passes while residual is $62K and duplicate rewards appear.','Deployment status treated as data acceptance','if deployment.success: publish()','Block publication/rollback as appropriate; require smoke, quality and reconciliation gates.'],
['Unbounded backfill changes millions of rows','Engineer replays all Bronze history to fix one day and changes 2.3M rows.','Backfill lacks bounded scope and blast-radius controls','source = spark.table("bronze_events")','Declare exact interval/snapshot, dry-run changed keys, prove idempotency, replay bounded scope, then reconcile.'],
['Restart destroys forensic evidence','Checkpoint directories are deleted before incident state is captured.','Recovery action taken before containment and diagnosis','rm(checkpoint_path, True)','Contain unsafe output, preserve offsets/checkpoints/logs/query IDs, establish timeline, then follow approved recovery.'],
['Analytics agent has excessive privilege','Natural-language analytics service runs with an ACCOUNTADMIN-like role.','No least-privilege execution boundary','role=ACCOUNTADMIN','Use read-only allowlisted semantic views, row/column policies, SELECT-only parser and separately authorized write actions.'],
['Jobs green but business telemetry missing','Monitoring has CPU and job success but no freshness, residual, duplicate or serving SLOs.','Observability stops at infrastructure metrics','monitor(job_status,cpu,memory)','Add business/data-product SLOs: freshness, controls, duplicates, p95 latency, drift and cost per outcome.'],
['Fraud model drift floods review queue','Review capacity is 500/day while model now flags 7,500/day.','Threshold/calibration no longer fits operations','flag = score >= 0.50','Assess feature/concept drift and calibration; choose threshold from review capacity and approved business cost.'],
['Agent attempts high-impact reward reversal','Agent tries to reverse 2,400 customer rewards automatically.','Agent authority boundary too broad','if confidence > .9: reverse_rewards(ids)','Require authorized human approval for bulk financial actions, typed tools, traceability and idempotent execution.'],
['Friday-night end-to-end cascade','Hot Kafka key → stream backlog → slow Snowflake MERGE → dbt late miss → stale API → duplicate rewards on replay.','Multiple interacting failures across the pipeline','scale_all(); restart_all(); publish_if_jobs_green()','Contain business effects, preserve evidence, diagnose each control point, repair in dependency order, bounded idempotent replay, reconcile, then reopen after acceptance.']
];
const host=document.getElementById('defects');if(!host)return;host.innerHTML='';
function show(i){const d=defects[i];document.getElementById('dtitle').textContent=(i+1)+'. '+d[0];document.getElementById('dsym').textContent=d[1];document.getElementById('dbad').textContent=d[3];const fb=document.getElementById('dfb'),opts=document.getElementById('dopts');fb.textContent='Choose a root cause.';opts.innerHTML='';const choices=[d[2],'Insufficient compute is always the root cause','Add DISTINCT at the final layer','Restart everything and clear state'].sort(()=>Math.random()-.5);choices.forEach(o=>{const b=document.createElement('button');b.textContent=o;b.style.display='block';b.style.margin='5px 0';b.onclick=()=>{const ok=o===d[2];fb.textContent=ok?'CORRECT — '+d[4]:'INCORRECT — Root cause: '+d[2]+' | Best repair: '+d[4];if(ok){let n=Number(localStorage.getItem('opsreadyDefectsCorrect')||0);localStorage.setItem('opsreadyDefectsCorrect',String(Math.min(30,n+1)))}};opts.appendChild(b)})}
defects.forEach((d,i)=>{const x=document.createElement('div');x.className='defect';x.innerHTML='<b>'+(i+1)+'. '+d[0]+'</b><div class="muted">'+d[1]+'</div>';x.onclick=()=>show(i);host.appendChild(x)});
window.OPSR_DEFECT_COUNT=defects.length;
})();